# ============ MySQL 测试环境 Secret ============
# 测试环境可以复用简单密码，生产环境请使用独立的强密码

apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: go-project-test
type: Opaque
data:
  mysql-root-password: MTIzNDU2   # 123456 的 base64
