# ============ user-srv 测试环境 Secret ============
#
# 测试环境可以复用简单密码，但和正式环境必须使用独立的 Secret（不同的 namespace 自动隔离）

apiVersion: v1
kind: Secret
metadata:
  name: user-srv-secret
  namespace: go-project-test
type: Opaque
stringData:
  mysql-password: "123456"
  jwt-secret: "k8s-test-secret"
