input {
  file {
    path => "/var/log/goapp/*.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    close_older => 3600
  }
}

filter {
  json {
    source => "message"
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "go-logstash-%{+yyyy.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}