// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/pb/coupon.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CouponService_ListCouponTemplates_FullMethodName = "/user.v1.CouponService/ListCouponTemplates"
	CouponService_ClaimCoupon_FullMethodName         = "/user.v1.CouponService/ClaimCoupon"
	CouponService_ListUserCoupons_FullMethodName     = "/user.v1.CouponService/ListUserCoupons"
	CouponService_GetAvailableCoupons_FullMethodName = "/user.v1.CouponService/GetAvailableCoupons"
	CouponService_UseCoupon_FullMethodName           = "/user.v1.CouponService/UseCoupon"
	CouponService_GetCouponDetail_FullMethodName     = "/user.v1.CouponService/GetCouponDetail"
)

// CouponServiceClient is the client API for CouponService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========================================
// 服务定义
// ========================================
type CouponServiceClient interface {
	// 获取可领取的优惠券列表
	ListCouponTemplates(ctx context.Context, in *ListCouponTemplatesRequest, opts ...grpc.CallOption) (*ListCouponTemplatesResponse, error)
	// 领取优惠券
	ClaimCoupon(ctx context.Context, in *ClaimCouponRequest, opts ...grpc.CallOption) (*ClaimCouponResponse, error)
	// 获取我的优惠券列表
	ListUserCoupons(ctx context.Context, in *ListUserCouponsRequest, opts ...grpc.CallOption) (*ListUserCouponsResponse, error)
	// 获取可用优惠券（下单时）
	GetAvailableCoupons(ctx context.Context, in *GetAvailableCouponsRequest, opts ...grpc.CallOption) (*GetAvailableCouponsResponse, error)
	// 使用优惠券
	UseCoupon(ctx context.Context, in *UseCouponRequest, opts ...grpc.CallOption) (*UseCouponResponse, error)
	// 获取优惠券详情
	GetCouponDetail(ctx context.Context, in *GetCouponDetailRequest, opts ...grpc.CallOption) (*GetCouponDetailResponse, error)
}

type couponServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCouponServiceClient(cc grpc.ClientConnInterface) CouponServiceClient {
	return &couponServiceClient{cc}
}

func (c *couponServiceClient) ListCouponTemplates(ctx context.Context, in *ListCouponTemplatesRequest, opts ...grpc.CallOption) (*ListCouponTemplatesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCouponTemplatesResponse)
	err := c.cc.Invoke(ctx, CouponService_ListCouponTemplates_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ClaimCoupon(ctx context.Context, in *ClaimCouponRequest, opts ...grpc.CallOption) (*ClaimCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimCouponResponse)
	err := c.cc.Invoke(ctx, CouponService_ClaimCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) ListUserCoupons(ctx context.Context, in *ListUserCouponsRequest, opts ...grpc.CallOption) (*ListUserCouponsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponsResponse)
	err := c.cc.Invoke(ctx, CouponService_ListUserCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) GetAvailableCoupons(ctx context.Context, in *GetAvailableCouponsRequest, opts ...grpc.CallOption) (*GetAvailableCouponsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAvailableCouponsResponse)
	err := c.cc.Invoke(ctx, CouponService_GetAvailableCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) UseCoupon(ctx context.Context, in *UseCouponRequest, opts ...grpc.CallOption) (*UseCouponResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseCouponResponse)
	err := c.cc.Invoke(ctx, CouponService_UseCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponServiceClient) GetCouponDetail(ctx context.Context, in *GetCouponDetailRequest, opts ...grpc.CallOption) (*GetCouponDetailResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCouponDetailResponse)
	err := c.cc.Invoke(ctx, CouponService_GetCouponDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServiceServer is the server API for CouponService service.
// All implementations must embed UnimplementedCouponServiceServer
// for forward compatibility.
//
// ========================================
// 服务定义
// ========================================
type CouponServiceServer interface {
	// 获取可领取的优惠券列表
	ListCouponTemplates(context.Context, *ListCouponTemplatesRequest) (*ListCouponTemplatesResponse, error)
	// 领取优惠券
	ClaimCoupon(context.Context, *ClaimCouponRequest) (*ClaimCouponResponse, error)
	// 获取我的优惠券列表
	ListUserCoupons(context.Context, *ListUserCouponsRequest) (*ListUserCouponsResponse, error)
	// 获取可用优惠券（下单时）
	GetAvailableCoupons(context.Context, *GetAvailableCouponsRequest) (*GetAvailableCouponsResponse, error)
	// 使用优惠券
	UseCoupon(context.Context, *UseCouponRequest) (*UseCouponResponse, error)
	// 获取优惠券详情
	GetCouponDetail(context.Context, *GetCouponDetailRequest) (*GetCouponDetailResponse, error)
	mustEmbedUnimplementedCouponServiceServer()
}

// UnimplementedCouponServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCouponServiceServer struct{}

func (UnimplementedCouponServiceServer) ListCouponTemplates(context.Context, *ListCouponTemplatesRequest) (*ListCouponTemplatesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCouponTemplates not implemented")
}
func (UnimplementedCouponServiceServer) ClaimCoupon(context.Context, *ClaimCouponRequest) (*ClaimCouponResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimCoupon not implemented")
}
func (UnimplementedCouponServiceServer) ListUserCoupons(context.Context, *ListUserCouponsRequest) (*ListUserCouponsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserCoupons not implemented")
}
func (UnimplementedCouponServiceServer) GetAvailableCoupons(context.Context, *GetAvailableCouponsRequest) (*GetAvailableCouponsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAvailableCoupons not implemented")
}
func (UnimplementedCouponServiceServer) UseCoupon(context.Context, *UseCouponRequest) (*UseCouponResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UseCoupon not implemented")
}
func (UnimplementedCouponServiceServer) GetCouponDetail(context.Context, *GetCouponDetailRequest) (*GetCouponDetailResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCouponDetail not implemented")
}
func (UnimplementedCouponServiceServer) mustEmbedUnimplementedCouponServiceServer() {}
func (UnimplementedCouponServiceServer) testEmbeddedByValue()                       {}

// UnsafeCouponServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouponServiceServer will
// result in compilation errors.
type UnsafeCouponServiceServer interface {
	mustEmbedUnimplementedCouponServiceServer()
}

func RegisterCouponServiceServer(s grpc.ServiceRegistrar, srv CouponServiceServer) {
	// If the following call panics, it indicates UnimplementedCouponServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CouponService_ServiceDesc, srv)
}

func _CouponService_ListCouponTemplates_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCouponTemplatesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListCouponTemplates(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListCouponTemplates_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListCouponTemplates(ctx, req.(*ListCouponTemplatesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ClaimCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ClaimCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ClaimCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ClaimCoupon(ctx, req.(*ClaimCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_ListUserCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).ListUserCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_ListUserCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).ListUserCoupons(ctx, req.(*ListUserCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_GetAvailableCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAvailableCouponsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).GetAvailableCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_GetAvailableCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).GetAvailableCoupons(ctx, req.(*GetAvailableCouponsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_UseCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseCouponRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).UseCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_UseCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).UseCoupon(ctx, req.(*UseCouponRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CouponService_GetCouponDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCouponDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServiceServer).GetCouponDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CouponService_GetCouponDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServiceServer).GetCouponDetail(ctx, req.(*GetCouponDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CouponService_ServiceDesc is the grpc.ServiceDesc for CouponService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CouponService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.CouponService",
	HandlerType: (*CouponServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListCouponTemplates",
			Handler:    _CouponService_ListCouponTemplates_Handler,
		},
		{
			MethodName: "ClaimCoupon",
			Handler:    _CouponService_ClaimCoupon_Handler,
		},
		{
			MethodName: "ListUserCoupons",
			Handler:    _CouponService_ListUserCoupons_Handler,
		},
		{
			MethodName: "GetAvailableCoupons",
			Handler:    _CouponService_GetAvailableCoupons_Handler,
		},
		{
			MethodName: "UseCoupon",
			Handler:    _CouponService_UseCoupon_Handler,
		},
		{
			MethodName: "GetCouponDetail",
			Handler:    _CouponService_GetCouponDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/coupon.proto",
}
