// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/pb/coupon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 优惠券模板
type CouponTemplate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`                                             // 优惠券名称
	Type           int32                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                                            // 类型：1=满减券 2=折扣券 3=无门槛券
	DiscountAmount float64                `protobuf:"fixed64,4,opt,name=discount_amount,json=discountAmount,proto3" json:"discount_amount,omitempty"` // 优惠金额（满减/无门槛）或折扣率（如0.85）
	MinAmount      float64                `protobuf:"fixed64,5,opt,name=min_amount,json=minAmount,proto3" json:"min_amount,omitempty"`                // 最低消费金额（满减券门槛）
	StartTime      string                 `protobuf:"bytes,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`                  // 有效期开始
	EndTime        string                 `protobuf:"bytes,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`                        // 有效期结束
	TotalCount     int32                  `protobuf:"varint,8,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`              // 发放总量（-1=无限制）
	ClaimedCount   int32                  `protobuf:"varint,9,opt,name=claimed_count,json=claimedCount,proto3" json:"claimed_count,omitempty"`        // 已领取数量
	PerUserLimit   int32                  `protobuf:"varint,10,opt,name=per_user_limit,json=perUserLimit,proto3" json:"per_user_limit,omitempty"`     // 每人限领数量
	Status         int32                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                                       // 状态：1=启用 0=禁用
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CouponTemplate) Reset() {
	*x = CouponTemplate{}
	mi := &file_api_pb_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponTemplate) ProtoMessage() {}

func (x *CouponTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponTemplate.ProtoReflect.Descriptor instead.
func (*CouponTemplate) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *CouponTemplate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponTemplate) GetType() int32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CouponTemplate) GetDiscountAmount() float64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CouponTemplate) GetMinAmount() float64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CouponTemplate) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *CouponTemplate) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *CouponTemplate) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CouponTemplate) GetClaimedCount() int32 {
	if x != nil {
		return x.ClaimedCount
	}
	return 0
}

func (x *CouponTemplate) GetPerUserLimit() int32 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *CouponTemplate) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 用户优惠券
type UserCoupon struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId    int64                  `protobuf:"varint,3,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`                       // 状态：1=未使用 2=已使用 3=已过期
	ClaimedAt     string                 `protobuf:"bytes,5,opt,name=claimed_at,json=claimedAt,proto3" json:"claimed_at,omitempty"` // 领取时间
	UsedAt        string                 `protobuf:"bytes,6,opt,name=used_at,json=usedAt,proto3" json:"used_at,omitempty"`          // 使用时间
	OrderId       string                 `protobuf:"bytes,7,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`       // 使用的订单ID
	Template      *CouponTemplate        `protobuf:"bytes,8,opt,name=template,proto3" json:"template,omitempty"`                    // 关联的模板信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserCoupon) Reset() {
	*x = UserCoupon{}
	mi := &file_api_pb_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoupon) ProtoMessage() {}

func (x *UserCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoupon.ProtoReflect.Descriptor instead.
func (*UserCoupon) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *UserCoupon) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCoupon) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCoupon) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *UserCoupon) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserCoupon) GetClaimedAt() string {
	if x != nil {
		return x.ClaimedAt
	}
	return ""
}

func (x *UserCoupon) GetUsedAt() string {
	if x != nil {
		return x.UsedAt
	}
	return ""
}

func (x *UserCoupon) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *UserCoupon) GetTemplate() *CouponTemplate {
	if x != nil {
		return x.Template
	}
	return nil
}

// ---------- 获取可领取的优惠券列表 ----------
type ListCouponTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"` // 页码
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"` // 每页条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponTemplatesRequest) Reset() {
	*x = ListCouponTemplatesRequest{}
	mi := &file_api_pb_coupon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponTemplatesRequest) ProtoMessage() {}

func (x *ListCouponTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponTemplatesRequest.ProtoReflect.Descriptor instead.
func (*ListCouponTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{2}
}

func (x *ListCouponTemplatesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListCouponTemplatesRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListCouponTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*CouponTemplate      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"` // 总条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCouponTemplatesResponse) Reset() {
	*x = ListCouponTemplatesResponse{}
	mi := &file_api_pb_coupon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCouponTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCouponTemplatesResponse) ProtoMessage() {}

func (x *ListCouponTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCouponTemplatesResponse.ProtoReflect.Descriptor instead.
func (*ListCouponTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{3}
}

func (x *ListCouponTemplatesResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListCouponTemplatesResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListCouponTemplatesResponse) GetData() []*CouponTemplate {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListCouponTemplatesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ---------- 领取优惠券 ----------
type ClaimCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TemplateId    int64                  `protobuf:"varint,2,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"` // 优惠券模板ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponRequest) Reset() {
	*x = ClaimCouponRequest{}
	mi := &file_api_pb_coupon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponRequest) ProtoMessage() {}

func (x *ClaimCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponRequest.ProtoReflect.Descriptor instead.
func (*ClaimCouponRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimCouponRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClaimCouponRequest) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

type ClaimCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Coupon        *UserCoupon            `protobuf:"bytes,3,opt,name=coupon,proto3" json:"coupon,omitempty"` // 返回领取的优惠券
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponResponse) Reset() {
	*x = ClaimCouponResponse{}
	mi := &file_api_pb_coupon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponResponse) ProtoMessage() {}

func (x *ClaimCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponResponse.ProtoReflect.Descriptor instead.
func (*ClaimCouponResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimCouponResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ClaimCouponResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ClaimCouponResponse) GetCoupon() *UserCoupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

// ---------- 获取我的优惠券列表 ----------
type ListUserCouponsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        int32                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` // 筛选状态：0=全部 1=未使用 2=已使用 3=已过期
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`     // 页码
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`     // 每页条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCouponsRequest) Reset() {
	*x = ListUserCouponsRequest{}
	mi := &file_api_pb_coupon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCouponsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsRequest) ProtoMessage() {}

func (x *ListUserCouponsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsRequest.ProtoReflect.Descriptor instead.
func (*ListUserCouponsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserCouponsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserCouponsRequest) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListUserCouponsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListUserCouponsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListUserCouponsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*UserCoupon          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"` // 总条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCouponsResponse) Reset() {
	*x = ListUserCouponsResponse{}
	mi := &file_api_pb_coupon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCouponsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsResponse) ProtoMessage() {}

func (x *ListUserCouponsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsResponse.ProtoReflect.Descriptor instead.
func (*ListUserCouponsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserCouponsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListUserCouponsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListUserCouponsResponse) GetData() []*UserCoupon {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListUserCouponsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ---------- 获取可用优惠券（下单时筛选） ----------
type GetAvailableCouponsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderAmount   float64                `protobuf:"fixed64,2,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"` // 订单金额
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableCouponsRequest) Reset() {
	*x = GetAvailableCouponsRequest{}
	mi := &file_api_pb_coupon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableCouponsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableCouponsRequest) ProtoMessage() {}

func (x *GetAvailableCouponsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableCouponsRequest.ProtoReflect.Descriptor instead.
func (*GetAvailableCouponsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{8}
}

func (x *GetAvailableCouponsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetAvailableCouponsRequest) GetOrderAmount() float64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

type GetAvailableCouponsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*UserCoupon          `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"` // 可用的优惠券列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAvailableCouponsResponse) Reset() {
	*x = GetAvailableCouponsResponse{}
	mi := &file_api_pb_coupon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAvailableCouponsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAvailableCouponsResponse) ProtoMessage() {}

func (x *GetAvailableCouponsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAvailableCouponsResponse.ProtoReflect.Descriptor instead.
func (*GetAvailableCouponsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{9}
}

func (x *GetAvailableCouponsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAvailableCouponsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetAvailableCouponsResponse) GetData() []*UserCoupon {
	if x != nil {
		return x.Data
	}
	return nil
}

// ---------- 使用优惠券 ----------
type UseCouponRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      int64                  `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"` // 用户优惠券ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	OrderId       string                 `protobuf:"bytes,3,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"` // 订单ID
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponRequest) Reset() {
	*x = UseCouponRequest{}
	mi := &file_api_pb_coupon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponRequest) ProtoMessage() {}

func (x *UseCouponRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponRequest.ProtoReflect.Descriptor instead.
func (*UseCouponRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{10}
}

func (x *UseCouponRequest) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *UseCouponRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UseCouponRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

type UseCouponResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponResponse) Reset() {
	*x = UseCouponResponse{}
	mi := &file_api_pb_coupon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponResponse) ProtoMessage() {}

func (x *UseCouponResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponResponse.ProtoReflect.Descriptor instead.
func (*UseCouponResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{11}
}

func (x *UseCouponResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UseCouponResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// ---------- 获取优惠券详情 ----------
type GetCouponDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponId      int64                  `protobuf:"varint,1,opt,name=coupon_id,json=couponId,proto3" json:"coupon_id,omitempty"` // 用户优惠券ID
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCouponDetailRequest) Reset() {
	*x = GetCouponDetailRequest{}
	mi := &file_api_pb_coupon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCouponDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponDetailRequest) ProtoMessage() {}

func (x *GetCouponDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponDetailRequest.ProtoReflect.Descriptor instead.
func (*GetCouponDetailRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{12}
}

func (x *GetCouponDetailRequest) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *GetCouponDetailRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetCouponDetailResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Coupon        *UserCoupon            `protobuf:"bytes,3,opt,name=coupon,proto3" json:"coupon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCouponDetailResponse) Reset() {
	*x = GetCouponDetailResponse{}
	mi := &file_api_pb_coupon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCouponDetailResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCouponDetailResponse) ProtoMessage() {}

func (x *GetCouponDetailResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_coupon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCouponDetailResponse.ProtoReflect.Descriptor instead.
func (*GetCouponDetailResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_coupon_proto_rawDescGZIP(), []int{13}
}

func (x *GetCouponDetailResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetCouponDetailResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetCouponDetailResponse) GetCoupon() *UserCoupon {
	if x != nil {
		return x.Coupon
	}
	return nil
}

var File_api_pb_coupon_proto protoreflect.FileDescriptor

const file_api_pb_coupon_proto_rawDesc = "" +
	"\n" +
	"\x13api/pb/coupon.proto\x12\auser.v1\"\xce\x02\n" +
	"\x0eCouponTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x05R\x04type\x12'\n" +
	"\x0fdiscount_amount\x18\x04 \x01(\x01R\x0ediscountAmount\x12\x1d\n" +
	"\n" +
	"min_amount\x18\x05 \x01(\x01R\tminAmount\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\tR\aendTime\x12\x1f\n" +
	"\vtotal_count\x18\b \x01(\x05R\n" +
	"totalCount\x12#\n" +
	"\rclaimed_count\x18\t \x01(\x05R\fclaimedCount\x12$\n" +
	"\x0eper_user_limit\x18\n" +
	" \x01(\x05R\fperUserLimit\x12\x16\n" +
	"\x06status\x18\v \x01(\x05R\x06status\"\xf6\x01\n" +
	"\n" +
	"UserCoupon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x03 \x01(\x03R\n" +
	"templateId\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"claimed_at\x18\x05 \x01(\tR\tclaimedAt\x12\x17\n" +
	"\aused_at\x18\x06 \x01(\tR\x06usedAt\x12\x19\n" +
	"\border_id\x18\a \x01(\tR\aorderId\x123\n" +
	"\btemplate\x18\b \x01(\v2\x17.user.v1.CouponTemplateR\btemplate\"D\n" +
	"\x1aListCouponTemplatesRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x86\x01\n" +
	"\x1bListCouponTemplatesResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.user.v1.CouponTemplateR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"N\n" +
	"\x12ClaimCouponRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x1f\n" +
	"\vtemplate_id\x18\x02 \x01(\x03R\n" +
	"templateId\"h\n" +
	"\x13ClaimCouponResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x06coupon\x18\x03 \x01(\v2\x13.user.v1.UserCouponR\x06coupon\"q\n" +
	"\x16ListUserCouponsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x05R\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"~\n" +
	"\x17ListUserCouponsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x04data\x18\x03 \x03(\v2\x13.user.v1.UserCouponR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"X\n" +
	"\x1aGetAvailableCouponsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12!\n" +
	"\forder_amount\x18\x02 \x01(\x01R\vorderAmount\"l\n" +
	"\x1bGetAvailableCouponsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12'\n" +
	"\x04data\x18\x03 \x03(\v2\x13.user.v1.UserCouponR\x04data\"c\n" +
	"\x10UseCouponRequest\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x03R\bcouponId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\border_id\x18\x03 \x01(\tR\aorderId\"9\n" +
	"\x11UseCouponResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"N\n" +
	"\x16GetCouponDetailRequest\x12\x1b\n" +
	"\tcoupon_id\x18\x01 \x01(\x03R\bcouponId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\"l\n" +
	"\x17GetCouponDetailResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x06coupon\x18\x03 \x01(\v2\x13.user.v1.UserCouponR\x06coupon2\x8d\x04\n" +
	"\rCouponService\x12`\n" +
	"\x13ListCouponTemplates\x12#.user.v1.ListCouponTemplatesRequest\x1a$.user.v1.ListCouponTemplatesResponse\x12H\n" +
	"\vClaimCoupon\x12\x1b.user.v1.ClaimCouponRequest\x1a\x1c.user.v1.ClaimCouponResponse\x12T\n" +
	"\x0fListUserCoupons\x12\x1f.user.v1.ListUserCouponsRequest\x1a .user.v1.ListUserCouponsResponse\x12`\n" +
	"\x13GetAvailableCoupons\x12#.user.v1.GetAvailableCouponsRequest\x1a$.user.v1.GetAvailableCouponsResponse\x12B\n" +
	"\tUseCoupon\x12\x19.user.v1.UseCouponRequest\x1a\x1a.user.v1.UseCouponResponse\x12T\n" +
	"\x0fGetCouponDetail\x12\x1f.user.v1.GetCouponDetailRequest\x1a .user.v1.GetCouponDetailResponseB\rZ\v./api/pb;pbb\x06proto3"

var (
	file_api_pb_coupon_proto_rawDescOnce sync.Once
	file_api_pb_coupon_proto_rawDescData []byte
)

func file_api_pb_coupon_proto_rawDescGZIP() []byte {
	file_api_pb_coupon_proto_rawDescOnce.Do(func() {
		file_api_pb_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pb_coupon_proto_rawDesc), len(file_api_pb_coupon_proto_rawDesc)))
	})
	return file_api_pb_coupon_proto_rawDescData
}

var file_api_pb_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_pb_coupon_proto_goTypes = []any{
	(*CouponTemplate)(nil),              // 0: user.v1.CouponTemplate
	(*UserCoupon)(nil),                  // 1: user.v1.UserCoupon
	(*ListCouponTemplatesRequest)(nil),  // 2: user.v1.ListCouponTemplatesRequest
	(*ListCouponTemplatesResponse)(nil), // 3: user.v1.ListCouponTemplatesResponse
	(*ClaimCouponRequest)(nil),          // 4: user.v1.ClaimCouponRequest
	(*ClaimCouponResponse)(nil),         // 5: user.v1.ClaimCouponResponse
	(*ListUserCouponsRequest)(nil),      // 6: user.v1.ListUserCouponsRequest
	(*ListUserCouponsResponse)(nil),     // 7: user.v1.ListUserCouponsResponse
	(*GetAvailableCouponsRequest)(nil),  // 8: user.v1.GetAvailableCouponsRequest
	(*GetAvailableCouponsResponse)(nil), // 9: user.v1.GetAvailableCouponsResponse
	(*UseCouponRequest)(nil),            // 10: user.v1.UseCouponRequest
	(*UseCouponResponse)(nil),           // 11: user.v1.UseCouponResponse
	(*GetCouponDetailRequest)(nil),      // 12: user.v1.GetCouponDetailRequest
	(*GetCouponDetailResponse)(nil),     // 13: user.v1.GetCouponDetailResponse
}
var file_api_pb_coupon_proto_depIdxs = []int32{
	0,  // 0: user.v1.UserCoupon.template:type_name -> user.v1.CouponTemplate
	0,  // 1: user.v1.ListCouponTemplatesResponse.data:type_name -> user.v1.CouponTemplate
	1,  // 2: user.v1.ClaimCouponResponse.coupon:type_name -> user.v1.UserCoupon
	1,  // 3: user.v1.ListUserCouponsResponse.data:type_name -> user.v1.UserCoupon
	1,  // 4: user.v1.GetAvailableCouponsResponse.data:type_name -> user.v1.UserCoupon
	1,  // 5: user.v1.GetCouponDetailResponse.coupon:type_name -> user.v1.UserCoupon
	2,  // 6: user.v1.CouponService.ListCouponTemplates:input_type -> user.v1.ListCouponTemplatesRequest
	4,  // 7: user.v1.CouponService.ClaimCoupon:input_type -> user.v1.ClaimCouponRequest
	6,  // 8: user.v1.CouponService.ListUserCoupons:input_type -> user.v1.ListUserCouponsRequest
	8,  // 9: user.v1.CouponService.GetAvailableCoupons:input_type -> user.v1.GetAvailableCouponsRequest
	10, // 10: user.v1.CouponService.UseCoupon:input_type -> user.v1.UseCouponRequest
	12, // 11: user.v1.CouponService.GetCouponDetail:input_type -> user.v1.GetCouponDetailRequest
	3,  // 12: user.v1.CouponService.ListCouponTemplates:output_type -> user.v1.ListCouponTemplatesResponse
	5,  // 13: user.v1.CouponService.ClaimCoupon:output_type -> user.v1.ClaimCouponResponse
	7,  // 14: user.v1.CouponService.ListUserCoupons:output_type -> user.v1.ListUserCouponsResponse
	9,  // 15: user.v1.CouponService.GetAvailableCoupons:output_type -> user.v1.GetAvailableCouponsResponse
	11, // 16: user.v1.CouponService.UseCoupon:output_type -> user.v1.UseCouponResponse
	13, // 17: user.v1.CouponService.GetCouponDetail:output_type -> user.v1.GetCouponDetailResponse
	12, // [12:18] is the sub-list for method output_type
	6,  // [6:12] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_pb_coupon_proto_init() }
func file_api_pb_coupon_proto_init() {
	if File_api_pb_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pb_coupon_proto_rawDesc), len(file_api_pb_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_coupon_proto_goTypes,
		DependencyIndexes: file_api_pb_coupon_proto_depIdxs,
		MessageInfos:      file_api_pb_coupon_proto_msgTypes,
	}.Build()
	File_api_pb_coupon_proto = out.File
	file_api_pb_coupon_proto_goTypes = nil
	file_api_pb_coupon_proto_depIdxs = nil
}
