// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/pb/member.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MemberLevel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	LevelName     string                 `protobuf:"bytes,2,opt,name=level_name,json=levelName,proto3" json:"level_name,omitempty"`     // 等级名称： 普通会员/银卡/金卡/钻石
	LevelValue    int32                  `protobuf:"varint,3,opt,name=level_value,json=levelValue,proto3" json:"level_value,omitempty"` // 等级值： 0/1/2/3
	MinGrowth     int32                  `protobuf:"varint,4,opt,name=min_growth,json=minGrowth,proto3" json:"min_growth,omitempty"`    // 最低成长值门槛
	MaxGrowth     int32                  `protobuf:"varint,5,opt,name=max_growth,json=maxGrowth,proto3" json:"max_growth,omitempty"`    // 最高成长值 （-1表示无上限）
	Discount      float64                `protobuf:"fixed64,6,opt,name=discount,proto3" json:"discount,omitempty"`                      // 折扣率 0.95 = 九五折
	Icon          string                 `protobuf:"bytes,7,opt,name=icon,proto3" json:"icon,omitempty"`                                // 等级图标 URL
	Description   string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`                  // 等级描述
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberLevel) Reset() {
	*x = MemberLevel{}
	mi := &file_api_pb_member_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberLevel) ProtoMessage() {}

func (x *MemberLevel) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberLevel.ProtoReflect.Descriptor instead.
func (*MemberLevel) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{0}
}

func (x *MemberLevel) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberLevel) GetLevelName() string {
	if x != nil {
		return x.LevelName
	}
	return ""
}

func (x *MemberLevel) GetLevelValue() int32 {
	if x != nil {
		return x.LevelValue
	}
	return 0
}

func (x *MemberLevel) GetMinGrowth() int32 {
	if x != nil {
		return x.MinGrowth
	}
	return 0
}

func (x *MemberLevel) GetMaxGrowth() int32 {
	if x != nil {
		return x.MaxGrowth
	}
	return 0
}

func (x *MemberLevel) GetDiscount() float64 {
	if x != nil {
		return x.Discount
	}
	return 0
}

func (x *MemberLevel) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

func (x *MemberLevel) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type MemberInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	LevelId       int64                  `protobuf:"varint,3,opt,name=level_id,json=levelId,proto3" json:"level_id,omitempty"`
	GrowthValue   int32                  `protobuf:"varint,4,opt,name=growth_value,json=growthValue,proto3" json:"growth_value,omitempty"`
	TotalGrowth   int32                  `protobuf:"varint,5,opt,name=total_growth,json=totalGrowth,proto3" json:"total_growth,omitempty"`
	LevelUpTime   string                 `protobuf:"bytes,6,opt,name=level_up_time,json=levelUpTime,proto3" json:"level_up_time,omitempty"` // 最近升级时间
	Level         *MemberLevel           `protobuf:"bytes,7,opt,name=level,proto3" json:"level,omitempty"`                                  // 关联等级信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberInfo) Reset() {
	*x = MemberInfo{}
	mi := &file_api_pb_member_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberInfo) ProtoMessage() {}

func (x *MemberInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberInfo.ProtoReflect.Descriptor instead.
func (*MemberInfo) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{1}
}

func (x *MemberInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *MemberInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *MemberInfo) GetLevelId() int64 {
	if x != nil {
		return x.LevelId
	}
	return 0
}

func (x *MemberInfo) GetGrowthValue() int32 {
	if x != nil {
		return x.GrowthValue
	}
	return 0
}

func (x *MemberInfo) GetTotalGrowth() int32 {
	if x != nil {
		return x.TotalGrowth
	}
	return 0
}

func (x *MemberInfo) GetLevelUpTime() string {
	if x != nil {
		return x.LevelUpTime
	}
	return ""
}

func (x *MemberInfo) GetLevel() *MemberLevel {
	if x != nil {
		return x.Level
	}
	return nil
}

// 成长值变动日志
type GrowthLog struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        int64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ChangeValue   int32                  `protobuf:"varint,3,opt,name=change_value,json=changeValue,proto3" json:"change_value,omitempty"` // 变动值 （正 = 增长， 负 = 减少）
	SourceType    string                 `protobuf:"bytes,4,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`     // 来源： order/review/signin/ admin
	SourceId      string                 `protobuf:"bytes,5,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`           // 来源 ID
	Description   string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`                     // 变动说明
	CreatedAt     string                 `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`        // 变动时间
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GrowthLog) Reset() {
	*x = GrowthLog{}
	mi := &file_api_pb_member_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GrowthLog) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GrowthLog) ProtoMessage() {}

func (x *GrowthLog) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GrowthLog.ProtoReflect.Descriptor instead.
func (*GrowthLog) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{2}
}

func (x *GrowthLog) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GrowthLog) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GrowthLog) GetChangeValue() int32 {
	if x != nil {
		return x.ChangeValue
	}
	return 0
}

func (x *GrowthLog) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *GrowthLog) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *GrowthLog) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *GrowthLog) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// ---------- 获取会员信息 ----------
type GetMemberInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberInfoRequest) Reset() {
	*x = GetMemberInfoRequest{}
	mi := &file_api_pb_member_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberInfoRequest) ProtoMessage() {}

func (x *GetMemberInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberInfoRequest.ProtoReflect.Descriptor instead.
func (*GetMemberInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{3}
}

func (x *GetMemberInfoRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetMemberInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Member        *MemberInfo            `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberInfoResponse) Reset() {
	*x = GetMemberInfoResponse{}
	mi := &file_api_pb_member_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberInfoResponse) ProtoMessage() {}

func (x *GetMemberInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberInfoResponse.ProtoReflect.Descriptor instead.
func (*GetMemberInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{4}
}

func (x *GetMemberInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMemberInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetMemberInfoResponse) GetMember() *MemberInfo {
	if x != nil {
		return x.Member
	}
	return nil
}

// ---------- 增加成长值 ----------
type AddGrowthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Growth        int32                  `protobuf:"varint,2,opt,name=growth,proto3" json:"growth,omitempty"`                          // 成长值（正数）
	SourceType    string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"` // 来源类型
	SourceId      string                 `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`       // 来源ID
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`                 // 来源说明
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGrowthRequest) Reset() {
	*x = AddGrowthRequest{}
	mi := &file_api_pb_member_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGrowthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGrowthRequest) ProtoMessage() {}

func (x *AddGrowthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGrowthRequest.ProtoReflect.Descriptor instead.
func (*AddGrowthRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{5}
}

func (x *AddGrowthRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddGrowthRequest) GetGrowth() int32 {
	if x != nil {
		return x.Growth
	}
	return 0
}

func (x *AddGrowthRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *AddGrowthRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *AddGrowthRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type AddGrowthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Member        *MemberInfo            `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"` // 返回更新后的会员信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGrowthResponse) Reset() {
	*x = AddGrowthResponse{}
	mi := &file_api_pb_member_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGrowthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGrowthResponse) ProtoMessage() {}

func (x *AddGrowthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGrowthResponse.ProtoReflect.Descriptor instead.
func (*AddGrowthResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{6}
}

func (x *AddGrowthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *AddGrowthResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *AddGrowthResponse) GetMember() *MemberInfo {
	if x != nil {
		return x.Member
	}
	return nil
}

// ---------- 扣减成长值（管理员/退款场景） ----------
type DeductGrowthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Growth        int32                  `protobuf:"varint,2,opt,name=growth,proto3" json:"growth,omitempty"` // 要扣减的成长值（正数，内部转负）
	SourceType    string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	SourceId      string                 `protobuf:"bytes,4,opt,name=source_id,json=sourceId,proto3" json:"source_id,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductGrowthRequest) Reset() {
	*x = DeductGrowthRequest{}
	mi := &file_api_pb_member_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductGrowthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductGrowthRequest) ProtoMessage() {}

func (x *DeductGrowthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductGrowthRequest.ProtoReflect.Descriptor instead.
func (*DeductGrowthRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{7}
}

func (x *DeductGrowthRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *DeductGrowthRequest) GetGrowth() int32 {
	if x != nil {
		return x.Growth
	}
	return 0
}

func (x *DeductGrowthRequest) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *DeductGrowthRequest) GetSourceId() string {
	if x != nil {
		return x.SourceId
	}
	return ""
}

func (x *DeductGrowthRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type DeductGrowthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Member        *MemberInfo            `protobuf:"bytes,3,opt,name=member,proto3" json:"member,omitempty"` // 返回更新后的会员信息
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeductGrowthResponse) Reset() {
	*x = DeductGrowthResponse{}
	mi := &file_api_pb_member_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeductGrowthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeductGrowthResponse) ProtoMessage() {}

func (x *DeductGrowthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeductGrowthResponse.ProtoReflect.Descriptor instead.
func (*DeductGrowthResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{8}
}

func (x *DeductGrowthResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeductGrowthResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *DeductGrowthResponse) GetMember() *MemberInfo {
	if x != nil {
		return x.Member
	}
	return nil
}

// ---------- 获取成长值变动日志 ----------
type GetGrowthLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"` // 页码
	Size          int32                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"` // 每页条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrowthLogsRequest) Reset() {
	*x = GetGrowthLogsRequest{}
	mi := &file_api_pb_member_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrowthLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrowthLogsRequest) ProtoMessage() {}

func (x *GetGrowthLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrowthLogsRequest.ProtoReflect.Descriptor instead.
func (*GetGrowthLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{9}
}

func (x *GetGrowthLogsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetGrowthLogsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetGrowthLogsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type GetGrowthLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*GrowthLog           `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int32                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"` // 总条数
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrowthLogsResponse) Reset() {
	*x = GetGrowthLogsResponse{}
	mi := &file_api_pb_member_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrowthLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrowthLogsResponse) ProtoMessage() {}

func (x *GetGrowthLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrowthLogsResponse.ProtoReflect.Descriptor instead.
func (*GetGrowthLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{10}
}

func (x *GetGrowthLogsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetGrowthLogsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetGrowthLogsResponse) GetData() []*GrowthLog {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GetGrowthLogsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// ---------- 获取会员权益列表 ----------
type GetMemberBenefitsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberBenefitsRequest) Reset() {
	*x = GetMemberBenefitsRequest{}
	mi := &file_api_pb_member_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberBenefitsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberBenefitsRequest) ProtoMessage() {}

func (x *GetMemberBenefitsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberBenefitsRequest.ProtoReflect.Descriptor instead.
func (*GetMemberBenefitsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{11}
}

func (x *GetMemberBenefitsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type Benefit struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`               // 权益名称
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"` // 权益描述
	Icon          string                 `protobuf:"bytes,3,opt,name=icon,proto3" json:"icon,omitempty"`               // 权益图标
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Benefit) Reset() {
	*x = Benefit{}
	mi := &file_api_pb_member_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Benefit) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Benefit) ProtoMessage() {}

func (x *Benefit) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Benefit.ProtoReflect.Descriptor instead.
func (*Benefit) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{12}
}

func (x *Benefit) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Benefit) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Benefit) GetIcon() string {
	if x != nil {
		return x.Icon
	}
	return ""
}

type GetMemberBenefitsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*Benefit             `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"` // 权益列表
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMemberBenefitsResponse) Reset() {
	*x = GetMemberBenefitsResponse{}
	mi := &file_api_pb_member_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMemberBenefitsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMemberBenefitsResponse) ProtoMessage() {}

func (x *GetMemberBenefitsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMemberBenefitsResponse.ProtoReflect.Descriptor instead.
func (*GetMemberBenefitsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{13}
}

func (x *GetMemberBenefitsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetMemberBenefitsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetMemberBenefitsResponse) GetData() []*Benefit {
	if x != nil {
		return x.Data
	}
	return nil
}

// ---------- 获取所有等级配置（含当前用户高亮） ----------
type ListMemberLevelsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemberLevelsRequest) Reset() {
	*x = ListMemberLevelsRequest{}
	mi := &file_api_pb_member_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemberLevelsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemberLevelsRequest) ProtoMessage() {}

func (x *ListMemberLevelsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemberLevelsRequest.ProtoReflect.Descriptor instead.
func (*ListMemberLevelsRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{14}
}

func (x *ListMemberLevelsRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ListMemberLevelsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*MemberLevel         `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	CurrentLevel  int32                  `protobuf:"varint,4,opt,name=current_level,json=currentLevel,proto3" json:"current_level,omitempty"` // 当前用户等级值
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMemberLevelsResponse) Reset() {
	*x = ListMemberLevelsResponse{}
	mi := &file_api_pb_member_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMemberLevelsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMemberLevelsResponse) ProtoMessage() {}

func (x *ListMemberLevelsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_member_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMemberLevelsResponse.ProtoReflect.Descriptor instead.
func (*ListMemberLevelsResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_member_proto_rawDescGZIP(), []int{15}
}

func (x *ListMemberLevelsResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListMemberLevelsResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListMemberLevelsResponse) GetData() []*MemberLevel {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListMemberLevelsResponse) GetCurrentLevel() int32 {
	if x != nil {
		return x.CurrentLevel
	}
	return 0
}

var File_api_pb_member_proto protoreflect.FileDescriptor

const file_api_pb_member_proto_rawDesc = "" +
	"\n" +
	"\x13api/pb/member.proto\x12\auser.v1\"\xed\x01\n" +
	"\vMemberLevel\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1d\n" +
	"\n" +
	"level_name\x18\x02 \x01(\tR\tlevelName\x12\x1f\n" +
	"\vlevel_value\x18\x03 \x01(\x05R\n" +
	"levelValue\x12\x1d\n" +
	"\n" +
	"min_growth\x18\x04 \x01(\x05R\tminGrowth\x12\x1d\n" +
	"\n" +
	"max_growth\x18\x05 \x01(\x05R\tmaxGrowth\x12\x1a\n" +
	"\bdiscount\x18\x06 \x01(\x01R\bdiscount\x12\x12\n" +
	"\x04icon\x18\a \x01(\tR\x04icon\x12 \n" +
	"\vdescription\x18\b \x01(\tR\vdescription\"\xe6\x01\n" +
	"\n" +
	"MemberInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12\x19\n" +
	"\blevel_id\x18\x03 \x01(\x03R\alevelId\x12!\n" +
	"\fgrowth_value\x18\x04 \x01(\x05R\vgrowthValue\x12!\n" +
	"\ftotal_growth\x18\x05 \x01(\x05R\vtotalGrowth\x12\"\n" +
	"\rlevel_up_time\x18\x06 \x01(\tR\vlevelUpTime\x12*\n" +
	"\x05level\x18\a \x01(\v2\x14.user.v1.MemberLevelR\x05level\"\xd6\x01\n" +
	"\tGrowthLog\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x03R\x06userId\x12!\n" +
	"\fchange_value\x18\x03 \x01(\x05R\vchangeValue\x12\x1f\n" +
	"\vsource_type\x18\x04 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x05 \x01(\tR\bsourceId\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\tR\tcreatedAt\"/\n" +
	"\x14GetMemberInfoRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"j\n" +
	"\x15GetMemberInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x06member\x18\x03 \x01(\v2\x13.user.v1.MemberInfoR\x06member\"\xa3\x01\n" +
	"\x10AddGrowthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06growth\x18\x02 \x01(\x05R\x06growth\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"f\n" +
	"\x11AddGrowthResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x06member\x18\x03 \x01(\v2\x13.user.v1.MemberInfoR\x06member\"\xa6\x01\n" +
	"\x13DeductGrowthRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06growth\x18\x02 \x01(\x05R\x06growth\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tsource_id\x18\x04 \x01(\tR\bsourceId\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"i\n" +
	"\x14DeductGrowthResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x06member\x18\x03 \x01(\v2\x13.user.v1.MemberInfoR\x06member\"W\n" +
	"\x14GetGrowthLogsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x05R\x04size\"{\n" +
	"\x15GetGrowthLogsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12&\n" +
	"\x04data\x18\x03 \x03(\v2\x12.user.v1.GrowthLogR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x05R\x05total\"3\n" +
	"\x18GetMemberBenefitsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"S\n" +
	"\aBenefit\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x12\n" +
	"\x04icon\x18\x03 \x01(\tR\x04icon\"g\n" +
	"\x19GetMemberBenefitsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12$\n" +
	"\x04data\x18\x03 \x03(\v2\x10.user.v1.BenefitR\x04data\"2\n" +
	"\x17ListMemberLevelsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\"\x8f\x01\n" +
	"\x18ListMemberLevelsResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12(\n" +
	"\x04data\x18\x03 \x03(\v2\x14.user.v1.MemberLevelR\x04data\x12#\n" +
	"\rcurrent_level\x18\x04 \x01(\x05R\fcurrentLevel2\xf5\x03\n" +
	"\rMemberService\x12N\n" +
	"\rGetMemberInfo\x12\x1d.user.v1.GetMemberInfoRequest\x1a\x1e.user.v1.GetMemberInfoResponse\x12B\n" +
	"\tAddGrowth\x12\x19.user.v1.AddGrowthRequest\x1a\x1a.user.v1.AddGrowthResponse\x12K\n" +
	"\fDeductGrowth\x12\x1c.user.v1.DeductGrowthRequest\x1a\x1d.user.v1.DeductGrowthResponse\x12N\n" +
	"\rGetGrowthLogs\x12\x1d.user.v1.GetGrowthLogsRequest\x1a\x1e.user.v1.GetGrowthLogsResponse\x12Z\n" +
	"\x11GetMemberBenefits\x12!.user.v1.GetMemberBenefitsRequest\x1a\".user.v1.GetMemberBenefitsResponse\x12W\n" +
	"\x10ListMemberLevels\x12 .user.v1.ListMemberLevelsRequest\x1a!.user.v1.ListMemberLevelsResponseB\rZ\v./api/pb;pbb\x06proto3"

var (
	file_api_pb_member_proto_rawDescOnce sync.Once
	file_api_pb_member_proto_rawDescData []byte
)

func file_api_pb_member_proto_rawDescGZIP() []byte {
	file_api_pb_member_proto_rawDescOnce.Do(func() {
		file_api_pb_member_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pb_member_proto_rawDesc), len(file_api_pb_member_proto_rawDesc)))
	})
	return file_api_pb_member_proto_rawDescData
}

var file_api_pb_member_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_pb_member_proto_goTypes = []any{
	(*MemberLevel)(nil),               // 0: user.v1.MemberLevel
	(*MemberInfo)(nil),                // 1: user.v1.MemberInfo
	(*GrowthLog)(nil),                 // 2: user.v1.GrowthLog
	(*GetMemberInfoRequest)(nil),      // 3: user.v1.GetMemberInfoRequest
	(*GetMemberInfoResponse)(nil),     // 4: user.v1.GetMemberInfoResponse
	(*AddGrowthRequest)(nil),          // 5: user.v1.AddGrowthRequest
	(*AddGrowthResponse)(nil),         // 6: user.v1.AddGrowthResponse
	(*DeductGrowthRequest)(nil),       // 7: user.v1.DeductGrowthRequest
	(*DeductGrowthResponse)(nil),      // 8: user.v1.DeductGrowthResponse
	(*GetGrowthLogsRequest)(nil),      // 9: user.v1.GetGrowthLogsRequest
	(*GetGrowthLogsResponse)(nil),     // 10: user.v1.GetGrowthLogsResponse
	(*GetMemberBenefitsRequest)(nil),  // 11: user.v1.GetMemberBenefitsRequest
	(*Benefit)(nil),                   // 12: user.v1.Benefit
	(*GetMemberBenefitsResponse)(nil), // 13: user.v1.GetMemberBenefitsResponse
	(*ListMemberLevelsRequest)(nil),   // 14: user.v1.ListMemberLevelsRequest
	(*ListMemberLevelsResponse)(nil),  // 15: user.v1.ListMemberLevelsResponse
}
var file_api_pb_member_proto_depIdxs = []int32{
	0,  // 0: user.v1.MemberInfo.level:type_name -> user.v1.MemberLevel
	1,  // 1: user.v1.GetMemberInfoResponse.member:type_name -> user.v1.MemberInfo
	1,  // 2: user.v1.AddGrowthResponse.member:type_name -> user.v1.MemberInfo
	1,  // 3: user.v1.DeductGrowthResponse.member:type_name -> user.v1.MemberInfo
	2,  // 4: user.v1.GetGrowthLogsResponse.data:type_name -> user.v1.GrowthLog
	12, // 5: user.v1.GetMemberBenefitsResponse.data:type_name -> user.v1.Benefit
	0,  // 6: user.v1.ListMemberLevelsResponse.data:type_name -> user.v1.MemberLevel
	3,  // 7: user.v1.MemberService.GetMemberInfo:input_type -> user.v1.GetMemberInfoRequest
	5,  // 8: user.v1.MemberService.AddGrowth:input_type -> user.v1.AddGrowthRequest
	7,  // 9: user.v1.MemberService.DeductGrowth:input_type -> user.v1.DeductGrowthRequest
	9,  // 10: user.v1.MemberService.GetGrowthLogs:input_type -> user.v1.GetGrowthLogsRequest
	11, // 11: user.v1.MemberService.GetMemberBenefits:input_type -> user.v1.GetMemberBenefitsRequest
	14, // 12: user.v1.MemberService.ListMemberLevels:input_type -> user.v1.ListMemberLevelsRequest
	4,  // 13: user.v1.MemberService.GetMemberInfo:output_type -> user.v1.GetMemberInfoResponse
	6,  // 14: user.v1.MemberService.AddGrowth:output_type -> user.v1.AddGrowthResponse
	8,  // 15: user.v1.MemberService.DeductGrowth:output_type -> user.v1.DeductGrowthResponse
	10, // 16: user.v1.MemberService.GetGrowthLogs:output_type -> user.v1.GetGrowthLogsResponse
	13, // 17: user.v1.MemberService.GetMemberBenefits:output_type -> user.v1.GetMemberBenefitsResponse
	15, // 18: user.v1.MemberService.ListMemberLevels:output_type -> user.v1.ListMemberLevelsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_pb_member_proto_init() }
func file_api_pb_member_proto_init() {
	if File_api_pb_member_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pb_member_proto_rawDesc), len(file_api_pb_member_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_member_proto_goTypes,
		DependencyIndexes: file_api_pb_member_proto_depIdxs,
		MessageInfos:      file_api_pb_member_proto_msgTypes,
	}.Build()
	File_api_pb_member_proto = out.File
	file_api_pb_member_proto_goTypes = nil
	file_api_pb_member_proto_depIdxs = nil
}
