// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/pb/member.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MemberService_GetMemberInfo_FullMethodName     = "/user.v1.MemberService/GetMemberInfo"
	MemberService_AddGrowth_FullMethodName         = "/user.v1.MemberService/AddGrowth"
	MemberService_DeductGrowth_FullMethodName      = "/user.v1.MemberService/DeductGrowth"
	MemberService_GetGrowthLogs_FullMethodName     = "/user.v1.MemberService/GetGrowthLogs"
	MemberService_GetMemberBenefits_FullMethodName = "/user.v1.MemberService/GetMemberBenefits"
	MemberService_ListMemberLevels_FullMethodName  = "/user.v1.MemberService/ListMemberLevels"
)

// MemberServiceClient is the client API for MemberService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ========================================
// 服务定义
// ========================================
type MemberServiceClient interface {
	// 获取用户会员信息
	GetMemberInfo(ctx context.Context, in *GetMemberInfoRequest, opts ...grpc.CallOption) (*GetMemberInfoResponse, error)
	// 增加成长值
	AddGrowth(ctx context.Context, in *AddGrowthRequest, opts ...grpc.CallOption) (*AddGrowthResponse, error)
	// 扣减成长值
	DeductGrowth(ctx context.Context, in *DeductGrowthRequest, opts ...grpc.CallOption) (*DeductGrowthResponse, error)
	// 获取成长值变动日志
	GetGrowthLogs(ctx context.Context, in *GetGrowthLogsRequest, opts ...grpc.CallOption) (*GetGrowthLogsResponse, error)
	// 获取会员权益
	GetMemberBenefits(ctx context.Context, in *GetMemberBenefitsRequest, opts ...grpc.CallOption) (*GetMemberBenefitsResponse, error)
	// 获取所有等级配置
	ListMemberLevels(ctx context.Context, in *ListMemberLevelsRequest, opts ...grpc.CallOption) (*ListMemberLevelsResponse, error)
}

type memberServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMemberServiceClient(cc grpc.ClientConnInterface) MemberServiceClient {
	return &memberServiceClient{cc}
}

func (c *memberServiceClient) GetMemberInfo(ctx context.Context, in *GetMemberInfoRequest, opts ...grpc.CallOption) (*GetMemberInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberInfoResponse)
	err := c.cc.Invoke(ctx, MemberService_GetMemberInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) AddGrowth(ctx context.Context, in *AddGrowthRequest, opts ...grpc.CallOption) (*AddGrowthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddGrowthResponse)
	err := c.cc.Invoke(ctx, MemberService_AddGrowth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) DeductGrowth(ctx context.Context, in *DeductGrowthRequest, opts ...grpc.CallOption) (*DeductGrowthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeductGrowthResponse)
	err := c.cc.Invoke(ctx, MemberService_DeductGrowth_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) GetGrowthLogs(ctx context.Context, in *GetGrowthLogsRequest, opts ...grpc.CallOption) (*GetGrowthLogsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGrowthLogsResponse)
	err := c.cc.Invoke(ctx, MemberService_GetGrowthLogs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) GetMemberBenefits(ctx context.Context, in *GetMemberBenefitsRequest, opts ...grpc.CallOption) (*GetMemberBenefitsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMemberBenefitsResponse)
	err := c.cc.Invoke(ctx, MemberService_GetMemberBenefits_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *memberServiceClient) ListMemberLevels(ctx context.Context, in *ListMemberLevelsRequest, opts ...grpc.CallOption) (*ListMemberLevelsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMemberLevelsResponse)
	err := c.cc.Invoke(ctx, MemberService_ListMemberLevels_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MemberServiceServer is the server API for MemberService service.
// All implementations must embed UnimplementedMemberServiceServer
// for forward compatibility.
//
// ========================================
// 服务定义
// ========================================
type MemberServiceServer interface {
	// 获取用户会员信息
	GetMemberInfo(context.Context, *GetMemberInfoRequest) (*GetMemberInfoResponse, error)
	// 增加成长值
	AddGrowth(context.Context, *AddGrowthRequest) (*AddGrowthResponse, error)
	// 扣减成长值
	DeductGrowth(context.Context, *DeductGrowthRequest) (*DeductGrowthResponse, error)
	// 获取成长值变动日志
	GetGrowthLogs(context.Context, *GetGrowthLogsRequest) (*GetGrowthLogsResponse, error)
	// 获取会员权益
	GetMemberBenefits(context.Context, *GetMemberBenefitsRequest) (*GetMemberBenefitsResponse, error)
	// 获取所有等级配置
	ListMemberLevels(context.Context, *ListMemberLevelsRequest) (*ListMemberLevelsResponse, error)
	mustEmbedUnimplementedMemberServiceServer()
}

// UnimplementedMemberServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMemberServiceServer struct{}

func (UnimplementedMemberServiceServer) GetMemberInfo(context.Context, *GetMemberInfoRequest) (*GetMemberInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberInfo not implemented")
}
func (UnimplementedMemberServiceServer) AddGrowth(context.Context, *AddGrowthRequest) (*AddGrowthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddGrowth not implemented")
}
func (UnimplementedMemberServiceServer) DeductGrowth(context.Context, *DeductGrowthRequest) (*DeductGrowthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeductGrowth not implemented")
}
func (UnimplementedMemberServiceServer) GetGrowthLogs(context.Context, *GetGrowthLogsRequest) (*GetGrowthLogsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGrowthLogs not implemented")
}
func (UnimplementedMemberServiceServer) GetMemberBenefits(context.Context, *GetMemberBenefitsRequest) (*GetMemberBenefitsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMemberBenefits not implemented")
}
func (UnimplementedMemberServiceServer) ListMemberLevels(context.Context, *ListMemberLevelsRequest) (*ListMemberLevelsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListMemberLevels not implemented")
}
func (UnimplementedMemberServiceServer) mustEmbedUnimplementedMemberServiceServer() {}
func (UnimplementedMemberServiceServer) testEmbeddedByValue()                       {}

// UnsafeMemberServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MemberServiceServer will
// result in compilation errors.
type UnsafeMemberServiceServer interface {
	mustEmbedUnimplementedMemberServiceServer()
}

func RegisterMemberServiceServer(s grpc.ServiceRegistrar, srv MemberServiceServer) {
	// If the following call panics, it indicates UnimplementedMemberServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MemberService_ServiceDesc, srv)
}

func _MemberService_GetMemberInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).GetMemberInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberService_GetMemberInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).GetMemberInfo(ctx, req.(*GetMemberInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_AddGrowth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddGrowthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).AddGrowth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberService_AddGrowth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).AddGrowth(ctx, req.(*AddGrowthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_DeductGrowth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeductGrowthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).DeductGrowth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberService_DeductGrowth_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).DeductGrowth(ctx, req.(*DeductGrowthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_GetGrowthLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGrowthLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).GetGrowthLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberService_GetGrowthLogs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).GetGrowthLogs(ctx, req.(*GetGrowthLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_GetMemberBenefits_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMemberBenefitsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).GetMemberBenefits(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberService_GetMemberBenefits_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).GetMemberBenefits(ctx, req.(*GetMemberBenefitsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MemberService_ListMemberLevels_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMemberLevelsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MemberServiceServer).ListMemberLevels(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MemberService_ListMemberLevels_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MemberServiceServer).ListMemberLevels(ctx, req.(*ListMemberLevelsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MemberService_ServiceDesc is the grpc.ServiceDesc for MemberService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MemberService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.MemberService",
	HandlerType: (*MemberServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMemberInfo",
			Handler:    _MemberService_GetMemberInfo_Handler,
		},
		{
			MethodName: "AddGrowth",
			Handler:    _MemberService_AddGrowth_Handler,
		},
		{
			MethodName: "DeductGrowth",
			Handler:    _MemberService_DeductGrowth_Handler,
		},
		{
			MethodName: "GetGrowthLogs",
			Handler:    _MemberService_GetGrowthLogs_Handler,
		},
		{
			MethodName: "GetMemberBenefits",
			Handler:    _MemberService_GetMemberBenefits_Handler,
		},
		{
			MethodName: "ListMemberLevels",
			Handler:    _MemberService_ListMemberLevels_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/member.proto",
}
