// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/pb/oauth.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 创建授权码
type CreateCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,2,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	UserId        uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCodeRequest) Reset() {
	*x = CreateCodeRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCodeRequest) ProtoMessage() {}

func (x *CreateCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCodeRequest.ProtoReflect.Descriptor instead.
func (*CreateCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCodeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateCodeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

func (x *CreateCodeRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *CreateCodeRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateCodeResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Code              int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`                                                   // 0=成功，其他=错误码
	Msg               string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`                                                      // 错误信息
	AuthorizationCode string                 `protobuf:"bytes,3,opt,name=authorization_code,json=authorizationCode,proto3" json:"authorization_code,omitempty"` // 授权码
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CreateCodeResponse) Reset() {
	*x = CreateCodeResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCodeResponse) ProtoMessage() {}

func (x *CreateCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCodeResponse.ProtoReflect.Descriptor instead.
func (*CreateCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCodeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateCodeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateCodeResponse) GetAuthorizationCode() string {
	if x != nil {
		return x.AuthorizationCode
	}
	return ""
}

// 验证授权码
type ValidateCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	RedirectUri   string                 `protobuf:"bytes,3,opt,name=redirect_uri,json=redirectUri,proto3" json:"redirect_uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCodeRequest) Reset() {
	*x = ValidateCodeRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCodeRequest) ProtoMessage() {}

func (x *ValidateCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCodeRequest.ProtoReflect.Descriptor instead.
func (*ValidateCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{2}
}

func (x *ValidateCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *ValidateCodeRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ValidateCodeRequest) GetRedirectUri() string {
	if x != nil {
		return x.RedirectUri
	}
	return ""
}

type ValidateCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCodeResponse) Reset() {
	*x = ValidateCodeResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCodeResponse) ProtoMessage() {}

func (x *ValidateCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCodeResponse.ProtoReflect.Descriptor instead.
func (*ValidateCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateCodeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ValidateCodeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ValidateCodeResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateCodeResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// 删除授权码（一次性使用后删除）
type DeleteCodeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCodeRequest) Reset() {
	*x = DeleteCodeRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCodeRequest) ProtoMessage() {}

func (x *DeleteCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCodeRequest.ProtoReflect.Descriptor instead.
func (*DeleteCodeRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

type DeleteCodeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCodeResponse) Reset() {
	*x = DeleteCodeResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCodeResponse) ProtoMessage() {}

func (x *DeleteCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCodeResponse.ProtoReflect.Descriptor instead.
func (*DeleteCodeResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteCodeResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *DeleteCodeResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 创建 Access Token
type CreateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	UserId        uint64                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Scope         string                 `protobuf:"bytes,3,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenRequest) Reset() {
	*x = CreateTokenRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenRequest) ProtoMessage() {}

func (x *CreateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenRequest.ProtoReflect.Descriptor instead.
func (*CreateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{6}
}

func (x *CreateTokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *CreateTokenRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateTokenRequest) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

type CreateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTokenResponse) Reset() {
	*x = CreateTokenResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTokenResponse) ProtoMessage() {}

func (x *CreateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTokenResponse.ProtoReflect.Descriptor instead.
func (*CreateTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{7}
}

func (x *CreateTokenResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateTokenResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *CreateTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *CreateTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *CreateTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 验证 Access Token
type ValidateTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenRequest) Reset() {
	*x = ValidateTokenRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenRequest) ProtoMessage() {}

func (x *ValidateTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenRequest.ProtoReflect.Descriptor instead.
func (*ValidateTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{8}
}

func (x *ValidateTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ClientId      string                 `protobuf:"bytes,4,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{9}
}

func (x *ValidateTokenResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ValidateTokenResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ValidateTokenResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ValidateTokenResponse) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ValidateTokenResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// 刷新 Token
type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ClientId      string                 `protobuf:"bytes,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{10}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	RefreshToken  string                 `protobuf:"bytes,4,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	ExpiresIn     int64                  `protobuf:"varint,5,opt,name=expires_in,json=expiresIn,proto3" json:"expires_in,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{11}
}

func (x *RefreshTokenResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RefreshTokenResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *RefreshTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

func (x *RefreshTokenResponse) GetExpiresIn() int64 {
	if x != nil {
		return x.ExpiresIn
	}
	return 0
}

// 撤销 Token
type RevokeTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenRequest) Reset() {
	*x = RevokeTokenRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenRequest) ProtoMessage() {}

func (x *RevokeTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenRequest.ProtoReflect.Descriptor instead.
func (*RevokeTokenRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{12}
}

func (x *RevokeTokenRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type RevokeTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeTokenResponse) Reset() {
	*x = RevokeTokenResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeTokenResponse) ProtoMessage() {}

func (x *RevokeTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeTokenResponse.ProtoReflect.Descriptor instead.
func (*RevokeTokenResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeTokenResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RevokeTokenResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

// 获取用户信息
type GetUserInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccessToken   string                 `protobuf:"bytes,1,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoRequest) Reset() {
	*x = GetUserInfoRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoRequest) ProtoMessage() {}

func (x *GetUserInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoRequest.ProtoReflect.Descriptor instead.
func (*GetUserInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{14}
}

func (x *GetUserInfoRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type GetUserInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	UserId        uint64                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Email         string                 `protobuf:"bytes,6,opt,name=email,proto3" json:"email,omitempty"`
	Scope         string                 `protobuf:"bytes,7,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInfoResponse) Reset() {
	*x = GetUserInfoResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInfoResponse) ProtoMessage() {}

func (x *GetUserInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInfoResponse.ProtoReflect.Descriptor instead.
func (*GetUserInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{15}
}

func (x *GetUserInfoResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetUserInfoResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetUserInfoResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserInfoResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserInfoResponse) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *GetUserInfoResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *GetUserInfoResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// 验证客户端
type ValidateClientRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ClientSecret  string                 `protobuf:"bytes,2,opt,name=client_secret,json=clientSecret,proto3" json:"client_secret,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateClientRequest) Reset() {
	*x = ValidateClientRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateClientRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientRequest) ProtoMessage() {}

func (x *ValidateClientRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientRequest.ProtoReflect.Descriptor instead.
func (*ValidateClientRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{16}
}

func (x *ValidateClientRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ValidateClientRequest) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type ValidateClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	RedirectUris  string                 `protobuf:"bytes,4,opt,name=redirect_uris,json=redirectUris,proto3" json:"redirect_uris,omitempty"`
	Scope         string                 `protobuf:"bytes,5,opt,name=scope,proto3" json:"scope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateClientResponse) Reset() {
	*x = ValidateClientResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateClientResponse) ProtoMessage() {}

func (x *ValidateClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateClientResponse.ProtoReflect.Descriptor instead.
func (*ValidateClientResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{17}
}

func (x *ValidateClientResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ValidateClientResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ValidateClientResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ValidateClientResponse) GetRedirectUris() string {
	if x != nil {
		return x.RedirectUris
	}
	return ""
}

func (x *ValidateClientResponse) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

// GitHub 登录
type GitHubLoginRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GithubCode    string                 `protobuf:"bytes,1,opt,name=github_code,json=githubCode,proto3" json:"github_code,omitempty"` // GitHub 授权码
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GitHubLoginRequest) Reset() {
	*x = GitHubLoginRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubLoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubLoginRequest) ProtoMessage() {}

func (x *GitHubLoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubLoginRequest.ProtoReflect.Descriptor instead.
func (*GitHubLoginRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{18}
}

func (x *GitHubLoginRequest) GetGithubCode() string {
	if x != nil {
		return x.GithubCode
	}
	return ""
}

type GitHubLoginResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Code           int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg            string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	NeedBind       bool                   `protobuf:"varint,3,opt,name=need_bind,json=needBind,proto3" json:"need_bind,omitempty"` // 是否需要绑定
	UserId         uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`       // 已绑定的用户 ID
	GithubId       int64                  `protobuf:"varint,5,opt,name=github_id,json=githubId,proto3" json:"github_id,omitempty"` // GitHub ID
	GithubUsername string                 `protobuf:"bytes,6,opt,name=github_username,json=githubUsername,proto3" json:"github_username,omitempty"`
	GithubEmail    string                 `protobuf:"bytes,7,opt,name=github_email,json=githubEmail,proto3" json:"github_email,omitempty"`
	AccessToken    string                 `protobuf:"bytes,8,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"` // JWT token（已绑定时返回）
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GitHubLoginResponse) Reset() {
	*x = GitHubLoginResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GitHubLoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GitHubLoginResponse) ProtoMessage() {}

func (x *GitHubLoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GitHubLoginResponse.ProtoReflect.Descriptor instead.
func (*GitHubLoginResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{19}
}

func (x *GitHubLoginResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GitHubLoginResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GitHubLoginResponse) GetNeedBind() bool {
	if x != nil {
		return x.NeedBind
	}
	return false
}

func (x *GitHubLoginResponse) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GitHubLoginResponse) GetGithubId() int64 {
	if x != nil {
		return x.GithubId
	}
	return 0
}

func (x *GitHubLoginResponse) GetGithubUsername() string {
	if x != nil {
		return x.GithubUsername
	}
	return ""
}

func (x *GitHubLoginResponse) GetGithubEmail() string {
	if x != nil {
		return x.GithubEmail
	}
	return ""
}

func (x *GitHubLoginResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// 绑定 GitHub 账号
type BindGitHubRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	GithubId       int64                  `protobuf:"varint,1,opt,name=github_id,json=githubId,proto3" json:"github_id,omitempty"`
	GithubUsername string                 `protobuf:"bytes,2,opt,name=github_username,json=githubUsername,proto3" json:"github_username,omitempty"`
	GithubEmail    string                 `protobuf:"bytes,3,opt,name=github_email,json=githubEmail,proto3" json:"github_email,omitempty"`
	UserId         uint64                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 要绑定的用户 ID
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BindGitHubRequest) Reset() {
	*x = BindGitHubRequest{}
	mi := &file_api_pb_oauth_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindGitHubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindGitHubRequest) ProtoMessage() {}

func (x *BindGitHubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindGitHubRequest.ProtoReflect.Descriptor instead.
func (*BindGitHubRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{20}
}

func (x *BindGitHubRequest) GetGithubId() int64 {
	if x != nil {
		return x.GithubId
	}
	return 0
}

func (x *BindGitHubRequest) GetGithubUsername() string {
	if x != nil {
		return x.GithubUsername
	}
	return ""
}

func (x *BindGitHubRequest) GetGithubEmail() string {
	if x != nil {
		return x.GithubEmail
	}
	return ""
}

func (x *BindGitHubRequest) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type BindGitHubResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindGitHubResponse) Reset() {
	*x = BindGitHubResponse{}
	mi := &file_api_pb_oauth_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindGitHubResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindGitHubResponse) ProtoMessage() {}

func (x *BindGitHubResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_oauth_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindGitHubResponse.ProtoReflect.Descriptor instead.
func (*BindGitHubResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_oauth_proto_rawDescGZIP(), []int{21}
}

func (x *BindGitHubResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BindGitHubResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_pb_oauth_proto protoreflect.FileDescriptor

const file_api_pb_oauth_proto_rawDesc = "" +
	"\n" +
	"\x12api/pb/oauth.proto\x12\auser.v1\"\x82\x01\n" +
	"\x11CreateCodeRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12!\n" +
	"\fredirect_uri\x18\x02 \x01(\tR\vredirectUri\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\"i\n" +
	"\x12CreateCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12-\n" +
	"\x12authorization_code\x18\x03 \x01(\tR\x11authorizationCode\"i\n" +
	"\x13ValidateCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\x12!\n" +
	"\fredirect_uri\x18\x03 \x01(\tR\vredirectUri\"k\n" +
	"\x14ValidateCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\"'\n" +
	"\x11DeleteCodeRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\":\n" +
	"\x12DeleteCodeResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"`\n" +
	"\x12CreateTokenRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\x04R\x06userId\x12\x14\n" +
	"\x05scope\x18\x03 \x01(\tR\x05scope\"\xa2\x01\n" +
	"\x13CreateTokenResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\x03R\texpiresIn\"9\n" +
	"\x14ValidateTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\x89\x01\n" +
	"\x15ValidateTokenResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tclient_id\x18\x04 \x01(\tR\bclientId\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\"W\n" +
	"\x13RefreshTokenRequest\x12#\n" +
	"\rrefresh_token\x18\x01 \x01(\tR\frefreshToken\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\tR\bclientId\"\xa3\x01\n" +
	"\x14RefreshTokenResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\x12#\n" +
	"\rrefresh_token\x18\x04 \x01(\tR\frefreshToken\x12\x1d\n" +
	"\n" +
	"expires_in\x18\x05 \x01(\x03R\texpiresIn\"7\n" +
	"\x12RevokeTokenRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\";\n" +
	"\x13RevokeTokenResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"7\n" +
	"\x12GetUserInfoRequest\x12!\n" +
	"\faccess_token\x18\x01 \x01(\tR\vaccessToken\"\xb2\x01\n" +
	"\x13GetUserInfoResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\x04R\x06userId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05email\x18\x06 \x01(\tR\x05email\x12\x14\n" +
	"\x05scope\x18\a \x01(\tR\x05scope\"Y\n" +
	"\x15ValidateClientRequest\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\x12#\n" +
	"\rclient_secret\x18\x02 \x01(\tR\fclientSecret\"\x8d\x01\n" +
	"\x16ValidateClientResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12#\n" +
	"\rredirect_uris\x18\x04 \x01(\tR\fredirectUris\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\tR\x05scope\"5\n" +
	"\x12GitHubLoginRequest\x12\x1f\n" +
	"\vgithub_code\x18\x01 \x01(\tR\n" +
	"githubCode\"\xfd\x01\n" +
	"\x13GitHubLoginResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12\x1b\n" +
	"\tneed_bind\x18\x03 \x01(\bR\bneedBind\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\x12\x1b\n" +
	"\tgithub_id\x18\x05 \x01(\x03R\bgithubId\x12'\n" +
	"\x0fgithub_username\x18\x06 \x01(\tR\x0egithubUsername\x12!\n" +
	"\fgithub_email\x18\a \x01(\tR\vgithubEmail\x12!\n" +
	"\faccess_token\x18\b \x01(\tR\vaccessToken\"\x95\x01\n" +
	"\x11BindGitHubRequest\x12\x1b\n" +
	"\tgithub_id\x18\x01 \x01(\x03R\bgithubId\x12'\n" +
	"\x0fgithub_username\x18\x02 \x01(\tR\x0egithubUsername\x12!\n" +
	"\fgithub_email\x18\x03 \x01(\tR\vgithubEmail\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\x04R\x06userId\":\n" +
	"\x12BindGitHubResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg2\x8f\a\n" +
	"\fOAuthService\x12R\n" +
	"\x17CreateAuthorizationCode\x12\x1a.user.v1.CreateCodeRequest\x1a\x1b.user.v1.CreateCodeResponse\x12X\n" +
	"\x19ValidateAuthorizationCode\x12\x1c.user.v1.ValidateCodeRequest\x1a\x1d.user.v1.ValidateCodeResponse\x12R\n" +
	"\x17DeleteAuthorizationCode\x12\x1a.user.v1.DeleteCodeRequest\x1a\x1b.user.v1.DeleteCodeResponse\x12N\n" +
	"\x11CreateAccessToken\x12\x1b.user.v1.CreateTokenRequest\x1a\x1c.user.v1.CreateTokenResponse\x12T\n" +
	"\x13ValidateAccessToken\x12\x1d.user.v1.ValidateTokenRequest\x1a\x1e.user.v1.ValidateTokenResponse\x12Q\n" +
	"\x12RefreshAccessToken\x12\x1c.user.v1.RefreshTokenRequest\x1a\x1d.user.v1.RefreshTokenResponse\x12H\n" +
	"\vRevokeToken\x12\x1b.user.v1.RevokeTokenRequest\x1a\x1c.user.v1.RevokeTokenResponse\x12O\n" +
	"\x12GetUserInfoByToken\x12\x1b.user.v1.GetUserInfoRequest\x1a\x1c.user.v1.GetUserInfoResponse\x12Q\n" +
	"\x0eValidateClient\x12\x1e.user.v1.ValidateClientRequest\x1a\x1f.user.v1.ValidateClientResponse\x12H\n" +
	"\vGitHubLogin\x12\x1b.user.v1.GitHubLoginRequest\x1a\x1c.user.v1.GitHubLoginResponse\x12L\n" +
	"\x11BindGitHubAccount\x12\x1a.user.v1.BindGitHubRequest\x1a\x1b.user.v1.BindGitHubResponseB\rZ\v./api/pb;pbb\x06proto3"

var (
	file_api_pb_oauth_proto_rawDescOnce sync.Once
	file_api_pb_oauth_proto_rawDescData []byte
)

func file_api_pb_oauth_proto_rawDescGZIP() []byte {
	file_api_pb_oauth_proto_rawDescOnce.Do(func() {
		file_api_pb_oauth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pb_oauth_proto_rawDesc), len(file_api_pb_oauth_proto_rawDesc)))
	})
	return file_api_pb_oauth_proto_rawDescData
}

var file_api_pb_oauth_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_api_pb_oauth_proto_goTypes = []any{
	(*CreateCodeRequest)(nil),      // 0: user.v1.CreateCodeRequest
	(*CreateCodeResponse)(nil),     // 1: user.v1.CreateCodeResponse
	(*ValidateCodeRequest)(nil),    // 2: user.v1.ValidateCodeRequest
	(*ValidateCodeResponse)(nil),   // 3: user.v1.ValidateCodeResponse
	(*DeleteCodeRequest)(nil),      // 4: user.v1.DeleteCodeRequest
	(*DeleteCodeResponse)(nil),     // 5: user.v1.DeleteCodeResponse
	(*CreateTokenRequest)(nil),     // 6: user.v1.CreateTokenRequest
	(*CreateTokenResponse)(nil),    // 7: user.v1.CreateTokenResponse
	(*ValidateTokenRequest)(nil),   // 8: user.v1.ValidateTokenRequest
	(*ValidateTokenResponse)(nil),  // 9: user.v1.ValidateTokenResponse
	(*RefreshTokenRequest)(nil),    // 10: user.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),   // 11: user.v1.RefreshTokenResponse
	(*RevokeTokenRequest)(nil),     // 12: user.v1.RevokeTokenRequest
	(*RevokeTokenResponse)(nil),    // 13: user.v1.RevokeTokenResponse
	(*GetUserInfoRequest)(nil),     // 14: user.v1.GetUserInfoRequest
	(*GetUserInfoResponse)(nil),    // 15: user.v1.GetUserInfoResponse
	(*ValidateClientRequest)(nil),  // 16: user.v1.ValidateClientRequest
	(*ValidateClientResponse)(nil), // 17: user.v1.ValidateClientResponse
	(*GitHubLoginRequest)(nil),     // 18: user.v1.GitHubLoginRequest
	(*GitHubLoginResponse)(nil),    // 19: user.v1.GitHubLoginResponse
	(*BindGitHubRequest)(nil),      // 20: user.v1.BindGitHubRequest
	(*BindGitHubResponse)(nil),     // 21: user.v1.BindGitHubResponse
}
var file_api_pb_oauth_proto_depIdxs = []int32{
	0,  // 0: user.v1.OAuthService.CreateAuthorizationCode:input_type -> user.v1.CreateCodeRequest
	2,  // 1: user.v1.OAuthService.ValidateAuthorizationCode:input_type -> user.v1.ValidateCodeRequest
	4,  // 2: user.v1.OAuthService.DeleteAuthorizationCode:input_type -> user.v1.DeleteCodeRequest
	6,  // 3: user.v1.OAuthService.CreateAccessToken:input_type -> user.v1.CreateTokenRequest
	8,  // 4: user.v1.OAuthService.ValidateAccessToken:input_type -> user.v1.ValidateTokenRequest
	10, // 5: user.v1.OAuthService.RefreshAccessToken:input_type -> user.v1.RefreshTokenRequest
	12, // 6: user.v1.OAuthService.RevokeToken:input_type -> user.v1.RevokeTokenRequest
	14, // 7: user.v1.OAuthService.GetUserInfoByToken:input_type -> user.v1.GetUserInfoRequest
	16, // 8: user.v1.OAuthService.ValidateClient:input_type -> user.v1.ValidateClientRequest
	18, // 9: user.v1.OAuthService.GitHubLogin:input_type -> user.v1.GitHubLoginRequest
	20, // 10: user.v1.OAuthService.BindGitHubAccount:input_type -> user.v1.BindGitHubRequest
	1,  // 11: user.v1.OAuthService.CreateAuthorizationCode:output_type -> user.v1.CreateCodeResponse
	3,  // 12: user.v1.OAuthService.ValidateAuthorizationCode:output_type -> user.v1.ValidateCodeResponse
	5,  // 13: user.v1.OAuthService.DeleteAuthorizationCode:output_type -> user.v1.DeleteCodeResponse
	7,  // 14: user.v1.OAuthService.CreateAccessToken:output_type -> user.v1.CreateTokenResponse
	9,  // 15: user.v1.OAuthService.ValidateAccessToken:output_type -> user.v1.ValidateTokenResponse
	11, // 16: user.v1.OAuthService.RefreshAccessToken:output_type -> user.v1.RefreshTokenResponse
	13, // 17: user.v1.OAuthService.RevokeToken:output_type -> user.v1.RevokeTokenResponse
	15, // 18: user.v1.OAuthService.GetUserInfoByToken:output_type -> user.v1.GetUserInfoResponse
	17, // 19: user.v1.OAuthService.ValidateClient:output_type -> user.v1.ValidateClientResponse
	19, // 20: user.v1.OAuthService.GitHubLogin:output_type -> user.v1.GitHubLoginResponse
	21, // 21: user.v1.OAuthService.BindGitHubAccount:output_type -> user.v1.BindGitHubResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_pb_oauth_proto_init() }
func file_api_pb_oauth_proto_init() {
	if File_api_pb_oauth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pb_oauth_proto_rawDesc), len(file_api_pb_oauth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_oauth_proto_goTypes,
		DependencyIndexes: file_api_pb_oauth_proto_depIdxs,
		MessageInfos:      file_api_pb_oauth_proto_msgTypes,
	}.Build()
	File_api_pb_oauth_proto = out.File
	file_api_pb_oauth_proto_goTypes = nil
	file_api_pb_oauth_proto_depIdxs = nil
}
