// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/pb/oauth.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OAuthService_CreateAuthorizationCode_FullMethodName   = "/user.v1.OAuthService/CreateAuthorizationCode"
	OAuthService_ValidateAuthorizationCode_FullMethodName = "/user.v1.OAuthService/ValidateAuthorizationCode"
	OAuthService_DeleteAuthorizationCode_FullMethodName   = "/user.v1.OAuthService/DeleteAuthorizationCode"
	OAuthService_CreateAccessToken_FullMethodName         = "/user.v1.OAuthService/CreateAccessToken"
	OAuthService_ValidateAccessToken_FullMethodName       = "/user.v1.OAuthService/ValidateAccessToken"
	OAuthService_RefreshAccessToken_FullMethodName        = "/user.v1.OAuthService/RefreshAccessToken"
	OAuthService_RevokeToken_FullMethodName               = "/user.v1.OAuthService/RevokeToken"
	OAuthService_GetUserInfoByToken_FullMethodName        = "/user.v1.OAuthService/GetUserInfoByToken"
	OAuthService_ValidateClient_FullMethodName            = "/user.v1.OAuthService/ValidateClient"
	OAuthService_GitHubLogin_FullMethodName               = "/user.v1.OAuthService/GitHubLogin"
	OAuthService_BindGitHubAccount_FullMethodName         = "/user.v1.OAuthService/BindGitHubAccount"
)

// OAuthServiceClient is the client API for OAuthService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// OAuth 服务定义
type OAuthServiceClient interface {
	// 1. 授权码相关
	CreateAuthorizationCode(ctx context.Context, in *CreateCodeRequest, opts ...grpc.CallOption) (*CreateCodeResponse, error)
	ValidateAuthorizationCode(ctx context.Context, in *ValidateCodeRequest, opts ...grpc.CallOption) (*ValidateCodeResponse, error)
	DeleteAuthorizationCode(ctx context.Context, in *DeleteCodeRequest, opts ...grpc.CallOption) (*DeleteCodeResponse, error)
	// 2. Token 相关
	CreateAccessToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*CreateTokenResponse, error)
	ValidateAccessToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
	RefreshAccessToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error)
	RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error)
	// 3. 用户信息
	GetUserInfoByToken(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error)
	// 4. 客户端验证
	ValidateClient(ctx context.Context, in *ValidateClientRequest, opts ...grpc.CallOption) (*ValidateClientResponse, error)
	// 5. GitHub 登录
	GitHubLogin(ctx context.Context, in *GitHubLoginRequest, opts ...grpc.CallOption) (*GitHubLoginResponse, error)
	BindGitHubAccount(ctx context.Context, in *BindGitHubRequest, opts ...grpc.CallOption) (*BindGitHubResponse, error)
}

type oAuthServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOAuthServiceClient(cc grpc.ClientConnInterface) OAuthServiceClient {
	return &oAuthServiceClient{cc}
}

func (c *oAuthServiceClient) CreateAuthorizationCode(ctx context.Context, in *CreateCodeRequest, opts ...grpc.CallOption) (*CreateCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCodeResponse)
	err := c.cc.Invoke(ctx, OAuthService_CreateAuthorizationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthServiceClient) ValidateAuthorizationCode(ctx context.Context, in *ValidateCodeRequest, opts ...grpc.CallOption) (*ValidateCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateCodeResponse)
	err := c.cc.Invoke(ctx, OAuthService_ValidateAuthorizationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthServiceClient) DeleteAuthorizationCode(ctx context.Context, in *DeleteCodeRequest, opts ...grpc.CallOption) (*DeleteCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCodeResponse)
	err := c.cc.Invoke(ctx, OAuthService_DeleteAuthorizationCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthServiceClient) CreateAccessToken(ctx context.Context, in *CreateTokenRequest, opts ...grpc.CallOption) (*CreateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTokenResponse)
	err := c.cc.Invoke(ctx, OAuthService_CreateAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthServiceClient) ValidateAccessToken(ctx context.Context, in *ValidateTokenRequest, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, OAuthService_ValidateAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthServiceClient) RefreshAccessToken(ctx context.Context, in *RefreshTokenRequest, opts ...grpc.CallOption) (*RefreshTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RefreshTokenResponse)
	err := c.cc.Invoke(ctx, OAuthService_RefreshAccessToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthServiceClient) RevokeToken(ctx context.Context, in *RevokeTokenRequest, opts ...grpc.CallOption) (*RevokeTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeTokenResponse)
	err := c.cc.Invoke(ctx, OAuthService_RevokeToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthServiceClient) GetUserInfoByToken(ctx context.Context, in *GetUserInfoRequest, opts ...grpc.CallOption) (*GetUserInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInfoResponse)
	err := c.cc.Invoke(ctx, OAuthService_GetUserInfoByToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthServiceClient) ValidateClient(ctx context.Context, in *ValidateClientRequest, opts ...grpc.CallOption) (*ValidateClientResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateClientResponse)
	err := c.cc.Invoke(ctx, OAuthService_ValidateClient_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthServiceClient) GitHubLogin(ctx context.Context, in *GitHubLoginRequest, opts ...grpc.CallOption) (*GitHubLoginResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GitHubLoginResponse)
	err := c.cc.Invoke(ctx, OAuthService_GitHubLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oAuthServiceClient) BindGitHubAccount(ctx context.Context, in *BindGitHubRequest, opts ...grpc.CallOption) (*BindGitHubResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindGitHubResponse)
	err := c.cc.Invoke(ctx, OAuthService_BindGitHubAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OAuthServiceServer is the server API for OAuthService service.
// All implementations must embed UnimplementedOAuthServiceServer
// for forward compatibility.
//
// OAuth 服务定义
type OAuthServiceServer interface {
	// 1. 授权码相关
	CreateAuthorizationCode(context.Context, *CreateCodeRequest) (*CreateCodeResponse, error)
	ValidateAuthorizationCode(context.Context, *ValidateCodeRequest) (*ValidateCodeResponse, error)
	DeleteAuthorizationCode(context.Context, *DeleteCodeRequest) (*DeleteCodeResponse, error)
	// 2. Token 相关
	CreateAccessToken(context.Context, *CreateTokenRequest) (*CreateTokenResponse, error)
	ValidateAccessToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error)
	RefreshAccessToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error)
	RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error)
	// 3. 用户信息
	GetUserInfoByToken(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error)
	// 4. 客户端验证
	ValidateClient(context.Context, *ValidateClientRequest) (*ValidateClientResponse, error)
	// 5. GitHub 登录
	GitHubLogin(context.Context, *GitHubLoginRequest) (*GitHubLoginResponse, error)
	BindGitHubAccount(context.Context, *BindGitHubRequest) (*BindGitHubResponse, error)
	mustEmbedUnimplementedOAuthServiceServer()
}

// UnimplementedOAuthServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOAuthServiceServer struct{}

func (UnimplementedOAuthServiceServer) CreateAuthorizationCode(context.Context, *CreateCodeRequest) (*CreateCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAuthorizationCode not implemented")
}
func (UnimplementedOAuthServiceServer) ValidateAuthorizationCode(context.Context, *ValidateCodeRequest) (*ValidateCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAuthorizationCode not implemented")
}
func (UnimplementedOAuthServiceServer) DeleteAuthorizationCode(context.Context, *DeleteCodeRequest) (*DeleteCodeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAuthorizationCode not implemented")
}
func (UnimplementedOAuthServiceServer) CreateAccessToken(context.Context, *CreateTokenRequest) (*CreateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAccessToken not implemented")
}
func (UnimplementedOAuthServiceServer) ValidateAccessToken(context.Context, *ValidateTokenRequest) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateAccessToken not implemented")
}
func (UnimplementedOAuthServiceServer) RefreshAccessToken(context.Context, *RefreshTokenRequest) (*RefreshTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshAccessToken not implemented")
}
func (UnimplementedOAuthServiceServer) RevokeToken(context.Context, *RevokeTokenRequest) (*RevokeTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeToken not implemented")
}
func (UnimplementedOAuthServiceServer) GetUserInfoByToken(context.Context, *GetUserInfoRequest) (*GetUserInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUserInfoByToken not implemented")
}
func (UnimplementedOAuthServiceServer) ValidateClient(context.Context, *ValidateClientRequest) (*ValidateClientResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateClient not implemented")
}
func (UnimplementedOAuthServiceServer) GitHubLogin(context.Context, *GitHubLoginRequest) (*GitHubLoginResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GitHubLogin not implemented")
}
func (UnimplementedOAuthServiceServer) BindGitHubAccount(context.Context, *BindGitHubRequest) (*BindGitHubResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindGitHubAccount not implemented")
}
func (UnimplementedOAuthServiceServer) mustEmbedUnimplementedOAuthServiceServer() {}
func (UnimplementedOAuthServiceServer) testEmbeddedByValue()                      {}

// UnsafeOAuthServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OAuthServiceServer will
// result in compilation errors.
type UnsafeOAuthServiceServer interface {
	mustEmbedUnimplementedOAuthServiceServer()
}

func RegisterOAuthServiceServer(s grpc.ServiceRegistrar, srv OAuthServiceServer) {
	// If the following call panics, it indicates UnimplementedOAuthServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OAuthService_ServiceDesc, srv)
}

func _OAuthService_CreateAuthorizationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).CreateAuthorizationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_CreateAuthorizationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).CreateAuthorizationCode(ctx, req.(*CreateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthService_ValidateAuthorizationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).ValidateAuthorizationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_ValidateAuthorizationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).ValidateAuthorizationCode(ctx, req.(*ValidateCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthService_DeleteAuthorizationCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).DeleteAuthorizationCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_DeleteAuthorizationCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).DeleteAuthorizationCode(ctx, req.(*DeleteCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthService_CreateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).CreateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_CreateAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).CreateAccessToken(ctx, req.(*CreateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthService_ValidateAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).ValidateAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_ValidateAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).ValidateAccessToken(ctx, req.(*ValidateTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthService_RefreshAccessToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).RefreshAccessToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_RefreshAccessToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).RefreshAccessToken(ctx, req.(*RefreshTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthService_RevokeToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).RevokeToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_RevokeToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).RevokeToken(ctx, req.(*RevokeTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthService_GetUserInfoByToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).GetUserInfoByToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_GetUserInfoByToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).GetUserInfoByToken(ctx, req.(*GetUserInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthService_ValidateClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateClientRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).ValidateClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_ValidateClient_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).ValidateClient(ctx, req.(*ValidateClientRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthService_GitHubLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GitHubLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).GitHubLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_GitHubLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).GitHubLogin(ctx, req.(*GitHubLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OAuthService_BindGitHubAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindGitHubRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OAuthServiceServer).BindGitHubAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OAuthService_BindGitHubAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OAuthServiceServer).BindGitHubAccount(ctx, req.(*BindGitHubRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OAuthService_ServiceDesc is the grpc.ServiceDesc for OAuthService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OAuthService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.OAuthService",
	HandlerType: (*OAuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAuthorizationCode",
			Handler:    _OAuthService_CreateAuthorizationCode_Handler,
		},
		{
			MethodName: "ValidateAuthorizationCode",
			Handler:    _OAuthService_ValidateAuthorizationCode_Handler,
		},
		{
			MethodName: "DeleteAuthorizationCode",
			Handler:    _OAuthService_DeleteAuthorizationCode_Handler,
		},
		{
			MethodName: "CreateAccessToken",
			Handler:    _OAuthService_CreateAccessToken_Handler,
		},
		{
			MethodName: "ValidateAccessToken",
			Handler:    _OAuthService_ValidateAccessToken_Handler,
		},
		{
			MethodName: "RefreshAccessToken",
			Handler:    _OAuthService_RefreshAccessToken_Handler,
		},
		{
			MethodName: "RevokeToken",
			Handler:    _OAuthService_RevokeToken_Handler,
		},
		{
			MethodName: "GetUserInfoByToken",
			Handler:    _OAuthService_GetUserInfoByToken_Handler,
		},
		{
			MethodName: "ValidateClient",
			Handler:    _OAuthService_ValidateClient_Handler,
		},
		{
			MethodName: "GitHubLogin",
			Handler:    _OAuthService_GitHubLogin_Handler,
		},
		{
			MethodName: "BindGitHubAccount",
			Handler:    _OAuthService_BindGitHubAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/oauth.proto",
}
