// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: api/pb/risk.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 黑名单相关
type AddBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	Source        string                 `protobuf:"bytes,3,opt,name=source,proto3" json:"source,omitempty"`                // 来源：manual/auto
	UserId        uint32                 `protobuf:"varint,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"` // 操作人
	Deadline      int64                  `protobuf:"varint,5,opt,name=deadline,proto3" json:"deadline,omitempty"`           // 过期时间戳，0=永久
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddBlacklistRequest) Reset() {
	*x = AddBlacklistRequest{}
	mi := &file_api_pb_risk_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlacklistRequest) ProtoMessage() {}

func (x *AddBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlacklistRequest.ProtoReflect.Descriptor instead.
func (*AddBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{0}
}

func (x *AddBlacklistRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AddBlacklistRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *AddBlacklistRequest) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *AddBlacklistRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *AddBlacklistRequest) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

type RemoveBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveBlacklistRequest) Reset() {
	*x = RemoveBlacklistRequest{}
	mi := &file_api_pb_risk_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlacklistRequest) ProtoMessage() {}

func (x *RemoveBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlacklistRequest.ProtoReflect.Descriptor instead.
func (*RemoveBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{1}
}

func (x *RemoveBlacklistRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ListBlacklistRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlacklistRequest) Reset() {
	*x = ListBlacklistRequest{}
	mi := &file_api_pb_risk_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlacklistRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlacklistRequest) ProtoMessage() {}

func (x *ListBlacklistRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlacklistRequest.ProtoReflect.Descriptor instead.
func (*ListBlacklistRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{2}
}

func (x *ListBlacklistRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListBlacklistRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListBlacklistResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*BlacklistItem       `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	Total         int64                  `protobuf:"varint,4,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListBlacklistResponse) Reset() {
	*x = ListBlacklistResponse{}
	mi := &file_api_pb_risk_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListBlacklistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlacklistResponse) ProtoMessage() {}

func (x *ListBlacklistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlacklistResponse.ProtoReflect.Descriptor instead.
func (*ListBlacklistResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{3}
}

func (x *ListBlacklistResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListBlacklistResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListBlacklistResponse) GetData() []*BlacklistItem {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ListBlacklistResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type BlacklistItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Ip            string                 `protobuf:"bytes,2,opt,name=ip,proto3" json:"ip,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	UserId        uint32                 `protobuf:"varint,5,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        bool                   `protobuf:"varint,6,opt,name=status,proto3" json:"status,omitempty"`
	Deadline      int64                  `protobuf:"varint,7,opt,name=deadline,proto3" json:"deadline,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlacklistItem) Reset() {
	*x = BlacklistItem{}
	mi := &file_api_pb_risk_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlacklistItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistItem) ProtoMessage() {}

func (x *BlacklistItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistItem.ProtoReflect.Descriptor instead.
func (*BlacklistItem) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{4}
}

func (x *BlacklistItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BlacklistItem) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *BlacklistItem) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *BlacklistItem) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *BlacklistItem) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BlacklistItem) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *BlacklistItem) GetDeadline() int64 {
	if x != nil {
		return x.Deadline
	}
	return 0
}

func (x *BlacklistItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

// 风控配置相关
type ListRiskConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRiskConfigRequest) Reset() {
	*x = ListRiskConfigRequest{}
	mi := &file_api_pb_risk_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRiskConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRiskConfigRequest) ProtoMessage() {}

func (x *ListRiskConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRiskConfigRequest.ProtoReflect.Descriptor instead.
func (*ListRiskConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{5}
}

type ListRiskConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data          []*RiskConfigItem      `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRiskConfigResponse) Reset() {
	*x = ListRiskConfigResponse{}
	mi := &file_api_pb_risk_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRiskConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRiskConfigResponse) ProtoMessage() {}

func (x *ListRiskConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRiskConfigResponse.ProtoReflect.Descriptor instead.
func (*ListRiskConfigResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{6}
}

func (x *ListRiskConfigResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListRiskConfigResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListRiskConfigResponse) GetData() []*RiskConfigItem {
	if x != nil {
		return x.Data
	}
	return nil
}

type RiskConfigItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleKey       string                 `protobuf:"bytes,2,opt,name=rule_key,json=ruleKey,proto3" json:"rule_key,omitempty"`
	RuleValue     string                 `protobuf:"bytes,3,opt,name=rule_value,json=ruleValue,proto3" json:"rule_value,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Status        bool                   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskConfigItem) Reset() {
	*x = RiskConfigItem{}
	mi := &file_api_pb_risk_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskConfigItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskConfigItem) ProtoMessage() {}

func (x *RiskConfigItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskConfigItem.ProtoReflect.Descriptor instead.
func (*RiskConfigItem) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{7}
}

func (x *RiskConfigItem) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RiskConfigItem) GetRuleKey() string {
	if x != nil {
		return x.RuleKey
	}
	return ""
}

func (x *RiskConfigItem) GetRuleValue() string {
	if x != nil {
		return x.RuleValue
	}
	return ""
}

func (x *RiskConfigItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RiskConfigItem) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

type UpdateRiskConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	RuleValue     string                 `protobuf:"bytes,2,opt,name=rule_value,json=ruleValue,proto3" json:"rule_value,omitempty"`
	Status        bool                   `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRiskConfigRequest) Reset() {
	*x = UpdateRiskConfigRequest{}
	mi := &file_api_pb_risk_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRiskConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRiskConfigRequest) ProtoMessage() {}

func (x *UpdateRiskConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRiskConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateRiskConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRiskConfigRequest) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateRiskConfigRequest) GetRuleValue() string {
	if x != nil {
		return x.RuleValue
	}
	return ""
}

func (x *UpdateRiskConfigRequest) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// 通用响应
type RiskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg           string                 `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RiskResponse) Reset() {
	*x = RiskResponse{}
	mi := &file_api_pb_risk_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RiskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiskResponse) ProtoMessage() {}

func (x *RiskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiskResponse.ProtoReflect.Descriptor instead.
func (*RiskResponse) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{9}
}

func (x *RiskResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *RiskResponse) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RefreshRiskConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshRiskConfigRequest) Reset() {
	*x = RefreshRiskConfigRequest{}
	mi := &file_api_pb_risk_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshRiskConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshRiskConfigRequest) ProtoMessage() {}

func (x *RefreshRiskConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pb_risk_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshRiskConfigRequest.ProtoReflect.Descriptor instead.
func (*RefreshRiskConfigRequest) Descriptor() ([]byte, []int) {
	return file_api_pb_risk_proto_rawDescGZIP(), []int{10}
}

var File_api_pb_risk_proto protoreflect.FileDescriptor

const file_api_pb_risk_proto_rawDesc = "" +
	"\n" +
	"\x11api/pb/risk.proto\x12\auser.v1\"\x8a\x01\n" +
	"\x13AddBlacklistRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12\x16\n" +
	"\x06source\x18\x03 \x01(\tR\x06source\x12\x17\n" +
	"\auser_id\x18\x04 \x01(\rR\x06userId\x12\x1a\n" +
	"\bdeadline\x18\x05 \x01(\x03R\bdeadline\"(\n" +
	"\x16RemoveBlacklistRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\">\n" +
	"\x14ListBlacklistRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"\x7f\n" +
	"\x15ListBlacklistResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12*\n" +
	"\x04data\x18\x03 \x03(\v2\x16.user.v1.BlacklistItemR\x04data\x12\x14\n" +
	"\x05total\x18\x04 \x01(\x03R\x05total\"\xcb\x01\n" +
	"\rBlacklistItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x17\n" +
	"\auser_id\x18\x05 \x01(\rR\x06userId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\bR\x06status\x12\x1a\n" +
	"\bdeadline\x18\a \x01(\x03R\bdeadline\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\tR\tcreatedAt\"\x17\n" +
	"\x15ListRiskConfigRequest\"k\n" +
	"\x16ListRiskConfigResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\x12+\n" +
	"\x04data\x18\x03 \x03(\v2\x17.user.v1.RiskConfigItemR\x04data\"\x94\x01\n" +
	"\x0eRiskConfigItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x19\n" +
	"\brule_key\x18\x02 \x01(\tR\aruleKey\x12\x1d\n" +
	"\n" +
	"rule_value\x18\x03 \x01(\tR\truleValue\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x05 \x01(\bR\x06status\"`\n" +
	"\x17UpdateRiskConfigRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x1d\n" +
	"\n" +
	"rule_value\x18\x02 \x01(\tR\truleValue\x12\x16\n" +
	"\x06status\x18\x03 \x01(\bR\x06status\"4\n" +
	"\fRiskResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x10\n" +
	"\x03msg\x18\x02 \x01(\tR\x03msg\"\x1a\n" +
	"\x18RefreshRiskConfigRequest2\xdc\x03\n" +
	"\vRiskService\x12C\n" +
	"\fAddBlacklist\x12\x1c.user.v1.AddBlacklistRequest\x1a\x15.user.v1.RiskResponse\x12I\n" +
	"\x0fRemoveBlacklist\x12\x1f.user.v1.RemoveBlacklistRequest\x1a\x15.user.v1.RiskResponse\x12N\n" +
	"\rListBlacklist\x12\x1d.user.v1.ListBlacklistRequest\x1a\x1e.user.v1.ListBlacklistResponse\x12Q\n" +
	"\x0eListRiskConfig\x12\x1e.user.v1.ListRiskConfigRequest\x1a\x1f.user.v1.ListRiskConfigResponse\x12K\n" +
	"\x10UpdateRiskConfig\x12 .user.v1.UpdateRiskConfigRequest\x1a\x15.user.v1.RiskResponse\x12M\n" +
	"\x11RefreshRiskConfig\x12!.user.v1.RefreshRiskConfigRequest\x1a\x15.user.v1.RiskResponseB\rZ\v./api/pb;pbb\x06proto3"

var (
	file_api_pb_risk_proto_rawDescOnce sync.Once
	file_api_pb_risk_proto_rawDescData []byte
)

func file_api_pb_risk_proto_rawDescGZIP() []byte {
	file_api_pb_risk_proto_rawDescOnce.Do(func() {
		file_api_pb_risk_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_pb_risk_proto_rawDesc), len(file_api_pb_risk_proto_rawDesc)))
	})
	return file_api_pb_risk_proto_rawDescData
}

var file_api_pb_risk_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_pb_risk_proto_goTypes = []any{
	(*AddBlacklistRequest)(nil),      // 0: user.v1.AddBlacklistRequest
	(*RemoveBlacklistRequest)(nil),   // 1: user.v1.RemoveBlacklistRequest
	(*ListBlacklistRequest)(nil),     // 2: user.v1.ListBlacklistRequest
	(*ListBlacklistResponse)(nil),    // 3: user.v1.ListBlacklistResponse
	(*BlacklistItem)(nil),            // 4: user.v1.BlacklistItem
	(*ListRiskConfigRequest)(nil),    // 5: user.v1.ListRiskConfigRequest
	(*ListRiskConfigResponse)(nil),   // 6: user.v1.ListRiskConfigResponse
	(*RiskConfigItem)(nil),           // 7: user.v1.RiskConfigItem
	(*UpdateRiskConfigRequest)(nil),  // 8: user.v1.UpdateRiskConfigRequest
	(*RiskResponse)(nil),             // 9: user.v1.RiskResponse
	(*RefreshRiskConfigRequest)(nil), // 10: user.v1.RefreshRiskConfigRequest
}
var file_api_pb_risk_proto_depIdxs = []int32{
	4,  // 0: user.v1.ListBlacklistResponse.data:type_name -> user.v1.BlacklistItem
	7,  // 1: user.v1.ListRiskConfigResponse.data:type_name -> user.v1.RiskConfigItem
	0,  // 2: user.v1.RiskService.AddBlacklist:input_type -> user.v1.AddBlacklistRequest
	1,  // 3: user.v1.RiskService.RemoveBlacklist:input_type -> user.v1.RemoveBlacklistRequest
	2,  // 4: user.v1.RiskService.ListBlacklist:input_type -> user.v1.ListBlacklistRequest
	5,  // 5: user.v1.RiskService.ListRiskConfig:input_type -> user.v1.ListRiskConfigRequest
	8,  // 6: user.v1.RiskService.UpdateRiskConfig:input_type -> user.v1.UpdateRiskConfigRequest
	10, // 7: user.v1.RiskService.RefreshRiskConfig:input_type -> user.v1.RefreshRiskConfigRequest
	9,  // 8: user.v1.RiskService.AddBlacklist:output_type -> user.v1.RiskResponse
	9,  // 9: user.v1.RiskService.RemoveBlacklist:output_type -> user.v1.RiskResponse
	3,  // 10: user.v1.RiskService.ListBlacklist:output_type -> user.v1.ListBlacklistResponse
	6,  // 11: user.v1.RiskService.ListRiskConfig:output_type -> user.v1.ListRiskConfigResponse
	9,  // 12: user.v1.RiskService.UpdateRiskConfig:output_type -> user.v1.RiskResponse
	9,  // 13: user.v1.RiskService.RefreshRiskConfig:output_type -> user.v1.RiskResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_pb_risk_proto_init() }
func file_api_pb_risk_proto_init() {
	if File_api_pb_risk_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_pb_risk_proto_rawDesc), len(file_api_pb_risk_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pb_risk_proto_goTypes,
		DependencyIndexes: file_api_pb_risk_proto_depIdxs,
		MessageInfos:      file_api_pb_risk_proto_msgTypes,
	}.Build()
	File_api_pb_risk_proto = out.File
	file_api_pb_risk_proto_goTypes = nil
	file_api_pb_risk_proto_depIdxs = nil
}
