// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: api/pb/risk.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RiskService_AddBlacklist_FullMethodName      = "/user.v1.RiskService/AddBlacklist"
	RiskService_RemoveBlacklist_FullMethodName   = "/user.v1.RiskService/RemoveBlacklist"
	RiskService_ListBlacklist_FullMethodName     = "/user.v1.RiskService/ListBlacklist"
	RiskService_ListRiskConfig_FullMethodName    = "/user.v1.RiskService/ListRiskConfig"
	RiskService_UpdateRiskConfig_FullMethodName  = "/user.v1.RiskService/UpdateRiskConfig"
	RiskService_RefreshRiskConfig_FullMethodName = "/user.v1.RiskService/RefreshRiskConfig"
)

// RiskServiceClient is the client API for RiskService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 风控服务
type RiskServiceClient interface {
	// 黑名单管理
	AddBlacklist(ctx context.Context, in *AddBlacklistRequest, opts ...grpc.CallOption) (*RiskResponse, error)
	RemoveBlacklist(ctx context.Context, in *RemoveBlacklistRequest, opts ...grpc.CallOption) (*RiskResponse, error)
	ListBlacklist(ctx context.Context, in *ListBlacklistRequest, opts ...grpc.CallOption) (*ListBlacklistResponse, error)
	// 风控配置管理
	ListRiskConfig(ctx context.Context, in *ListRiskConfigRequest, opts ...grpc.CallOption) (*ListRiskConfigResponse, error)
	UpdateRiskConfig(ctx context.Context, in *UpdateRiskConfigRequest, opts ...grpc.CallOption) (*RiskResponse, error)
	// 热更新
	RefreshRiskConfig(ctx context.Context, in *RefreshRiskConfigRequest, opts ...grpc.CallOption) (*RiskResponse, error)
}

type riskServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRiskServiceClient(cc grpc.ClientConnInterface) RiskServiceClient {
	return &riskServiceClient{cc}
}

func (c *riskServiceClient) AddBlacklist(ctx context.Context, in *AddBlacklistRequest, opts ...grpc.CallOption) (*RiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, RiskService_AddBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) RemoveBlacklist(ctx context.Context, in *RemoveBlacklistRequest, opts ...grpc.CallOption) (*RiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, RiskService_RemoveBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) ListBlacklist(ctx context.Context, in *ListBlacklistRequest, opts ...grpc.CallOption) (*ListBlacklistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBlacklistResponse)
	err := c.cc.Invoke(ctx, RiskService_ListBlacklist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) ListRiskConfig(ctx context.Context, in *ListRiskConfigRequest, opts ...grpc.CallOption) (*ListRiskConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRiskConfigResponse)
	err := c.cc.Invoke(ctx, RiskService_ListRiskConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) UpdateRiskConfig(ctx context.Context, in *UpdateRiskConfigRequest, opts ...grpc.CallOption) (*RiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, RiskService_UpdateRiskConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *riskServiceClient) RefreshRiskConfig(ctx context.Context, in *RefreshRiskConfigRequest, opts ...grpc.CallOption) (*RiskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RiskResponse)
	err := c.cc.Invoke(ctx, RiskService_RefreshRiskConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RiskServiceServer is the server API for RiskService service.
// All implementations must embed UnimplementedRiskServiceServer
// for forward compatibility.
//
// 风控服务
type RiskServiceServer interface {
	// 黑名单管理
	AddBlacklist(context.Context, *AddBlacklistRequest) (*RiskResponse, error)
	RemoveBlacklist(context.Context, *RemoveBlacklistRequest) (*RiskResponse, error)
	ListBlacklist(context.Context, *ListBlacklistRequest) (*ListBlacklistResponse, error)
	// 风控配置管理
	ListRiskConfig(context.Context, *ListRiskConfigRequest) (*ListRiskConfigResponse, error)
	UpdateRiskConfig(context.Context, *UpdateRiskConfigRequest) (*RiskResponse, error)
	// 热更新
	RefreshRiskConfig(context.Context, *RefreshRiskConfigRequest) (*RiskResponse, error)
	mustEmbedUnimplementedRiskServiceServer()
}

// UnimplementedRiskServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRiskServiceServer struct{}

func (UnimplementedRiskServiceServer) AddBlacklist(context.Context, *AddBlacklistRequest) (*RiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddBlacklist not implemented")
}
func (UnimplementedRiskServiceServer) RemoveBlacklist(context.Context, *RemoveBlacklistRequest) (*RiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveBlacklist not implemented")
}
func (UnimplementedRiskServiceServer) ListBlacklist(context.Context, *ListBlacklistRequest) (*ListBlacklistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBlacklist not implemented")
}
func (UnimplementedRiskServiceServer) ListRiskConfig(context.Context, *ListRiskConfigRequest) (*ListRiskConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRiskConfig not implemented")
}
func (UnimplementedRiskServiceServer) UpdateRiskConfig(context.Context, *UpdateRiskConfigRequest) (*RiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRiskConfig not implemented")
}
func (UnimplementedRiskServiceServer) RefreshRiskConfig(context.Context, *RefreshRiskConfigRequest) (*RiskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefreshRiskConfig not implemented")
}
func (UnimplementedRiskServiceServer) mustEmbedUnimplementedRiskServiceServer() {}
func (UnimplementedRiskServiceServer) testEmbeddedByValue()                     {}

// UnsafeRiskServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RiskServiceServer will
// result in compilation errors.
type UnsafeRiskServiceServer interface {
	mustEmbedUnimplementedRiskServiceServer()
}

func RegisterRiskServiceServer(s grpc.ServiceRegistrar, srv RiskServiceServer) {
	// If the following call panics, it indicates UnimplementedRiskServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RiskService_ServiceDesc, srv)
}

func _RiskService_AddBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).AddBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_AddBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).AddBlacklist(ctx, req.(*AddBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_RemoveBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).RemoveBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_RemoveBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).RemoveBlacklist(ctx, req.(*RemoveBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_ListBlacklist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlacklistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).ListBlacklist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_ListBlacklist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).ListBlacklist(ctx, req.(*ListBlacklistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_ListRiskConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRiskConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).ListRiskConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_ListRiskConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).ListRiskConfig(ctx, req.(*ListRiskConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_UpdateRiskConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRiskConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).UpdateRiskConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_UpdateRiskConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).UpdateRiskConfig(ctx, req.(*UpdateRiskConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RiskService_RefreshRiskConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefreshRiskConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RiskServiceServer).RefreshRiskConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RiskService_RefreshRiskConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RiskServiceServer).RefreshRiskConfig(ctx, req.(*RefreshRiskConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RiskService_ServiceDesc is the grpc.ServiceDesc for RiskService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RiskService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "user.v1.RiskService",
	HandlerType: (*RiskServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddBlacklist",
			Handler:    _RiskService_AddBlacklist_Handler,
		},
		{
			MethodName: "RemoveBlacklist",
			Handler:    _RiskService_RemoveBlacklist_Handler,
		},
		{
			MethodName: "ListBlacklist",
			Handler:    _RiskService_ListBlacklist_Handler,
		},
		{
			MethodName: "ListRiskConfig",
			Handler:    _RiskService_ListRiskConfig_Handler,
		},
		{
			MethodName: "UpdateRiskConfig",
			Handler:    _RiskService_UpdateRiskConfig_Handler,
		},
		{
			MethodName: "RefreshRiskConfig",
			Handler:    _RiskService_RefreshRiskConfig_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/pb/risk.proto",
}
